#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pskiplist_root="$(dirname "$script_dir")"
out="$pskiplist_root/include/pskiplist/pskiplist.hpp"

if ! command -v quom >/dev/null 2>&1; then
  echo "warning: quom not found on PATH, skipping pskiplist.hpp regeneration." >&2
  echo "  install it with: pipx install quom  (or: pip install --user quom)" >&2
  exit 0
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

quom -I "$pskiplist_root/include" \
  "$pskiplist_root/include/pskiplist/pskiplist_dev.hpp" \
  "$tmp"

{
  echo "// Generated by scripts/amalgamate.sh from include/pskiplist/detail/*.hpp. Do not edit"
  echo "// directly — edit the sources under detail/ and regenerate."
  cat "$tmp"
} > "$out"
