#pragma once

#define PSKIPLIST_VERSION_MAJOR 0
#define PSKIPLIST_VERSION_MINOR 1
#define PSKIPLIST_VERSION_PATCH 0
#define PSKIPLIST_VERSION (PSKIPLIST_VERSION_MAJOR * 10000 + PSKIPLIST_VERSION_MINOR * 100 + PSKIPLIST_VERSION_PATCH)
