// Generated by scripts/amalgamate.sh from include/pskiplist/detail/*.hpp. Do not edit
// directly — edit the sources under detail/ and regenerate.
#pragma once

#include <concepts>
#include <type_traits>

namespace pskiplist {

// Key is stored as raw bytes directly in the mmap'd file (2.1節) and is never
// placement-new constructed slot-by-slot — only trivially copyable types can be safely
// read from and overwritten onto memory that was never explicitly constructed.
template <typename Key>
concept SkipListKey = std::is_trivially_copyable_v<Key> && std::default_initializable<Key>;

template <typename Compare, typename Key>
concept SkipListCompare = std::default_initializable<Compare> && std::predicate<Compare, const Key &, const Key &>;

}  // namespace pskiplist

#include <atomic>
#include <cstdint>

#include <cstdint>

namespace pskiplist {

using Offset = uint64_t;
inline constexpr uint64_t kForwardMarkBit = uint64_t{1} << 63;
inline constexpr Offset kNullOffset = kForwardMarkBit - 1;

[[nodiscard]] inline constexpr auto pack_forward(Offset offset, bool marked) -> uint64_t {
  return offset | (marked ? kForwardMarkBit : uint64_t{0});
}
[[nodiscard]] inline constexpr auto forward_offset(uint64_t raw) -> Offset { return raw & ~kForwardMarkBit; }
[[nodiscard]] inline constexpr auto forward_marked(uint64_t raw) -> bool { return (raw & kForwardMarkBit) != 0; }

// A tagged (offset, generation counter) pair packed into one word, for the free list's
// Treiber stack head: the counter changes on every push and pop so a thread that stalls
// mid-pop with a stale head value can never CAS it back in undetected, even if the exact
// same offset has since been popped and pushed again (the classic ABA hazard for a plain
// offset-only stack head). 24 bits of counter is generous — wrapping it back to a value
// a stalled thread could still match would need that many free-list push/pop cycles to
// land on the same offset again during a single stall, which isn't realistic. 40 bits of
// offset is equally generous for node counts.
inline constexpr int kTaggedOffsetBits = 40;
inline constexpr uint64_t kTaggedOffsetMask = (uint64_t{1} << kTaggedOffsetBits) - 1;
inline constexpr Offset kMaxTaggedOffset = kTaggedOffsetMask;

inline constexpr uint32_t kTaggedGenerationMask = (uint32_t{1} << (64 - kTaggedOffsetBits)) - 1;

[[nodiscard]] inline constexpr auto pack_tagged(Offset offset, uint32_t tag) -> uint64_t {
  return (offset & kTaggedOffsetMask) | (static_cast<uint64_t>(tag & kTaggedGenerationMask) << kTaggedOffsetBits);
}
[[nodiscard]] inline constexpr auto tagged_offset(uint64_t raw) -> Offset { return raw & kTaggedOffsetMask; }
[[nodiscard]] inline constexpr auto tagged_generation(uint64_t raw) -> uint32_t {
  return static_cast<uint32_t>(raw >> kTaggedOffsetBits);
}

}  // namespace pskiplist

namespace pskiplist {

template <typename Key>
struct DurableNode {
  std::atomic<uint64_t> epoch{0};  // creation epoch — never touched again after allocation
  Key key{};
  std::atomic<uint64_t> value{0};
  // Shadow of `value` as of the last checkpoint that covers it, and the epoch of the most
  // recent mutation — see skiplist.hpp's shadow_if_first_touch_since_checkpoint() and
  // recover().
  std::atomic<uint64_t> checkpointed_value{0};
  std::atomic<uint64_t> mutation_epoch{0};
  mutable std::atomic<uint64_t> forward0{pack_forward(kNullOffset, false)};
  // Linkage and dedup guard for the checkpoint-gated physical-unlink queue — see
  // enqueue_pending_checkpoint_unlink() in skiplist.hpp.
  std::atomic<Offset> next_checkpoint_unlink{kNullOffset};
  std::atomic<bool> pending_checkpoint_unlink_queued{false};
};

}  // namespace pskiplist

#include <array>
#include <atomic>
#include <cstdint>

namespace pskiplist {

enum class EpochRole : uint8_t {
  kReader,
  kWriter,
};

// Per-parity-slot active counts, split by role. reclaim() (2.3節) waits for both readers
// and writers in a slot to drain, since either could hold a stale offset reference to a
// node about to be freed. checkpoint() (3章) waits only for writers, since a concurrent
// reader never mutates anything msync() could tear.
struct EpochSlot {
  std::atomic<int64_t> readers{0};
  std::atomic<int64_t> writers{0};
};

// RAII registration for a 2-slot epoch-based reclamation scheme: registers into whichever
// of `slots[0]`/`slots[1]` matches the current parity of `epoch` for the token's lifetime,
// under the counter matching `role`. Whoever advances `epoch` and waits for the slot the
// advance vacated to drain treats anything observed under it as safe to act on.
class EpochToken {
 public:
  // Reading `epoch` and incrementing that parity's counter is not one atomic step: a thread
  // can load `epoch`, then stall (preemption) before its fetch_add lands. reclaim() can drain
  // that exact slot's count as 0 in the meantime, decide it's safe, and free memory this
  // thread is about to walk into once it resumes. Guard against that by re-reading `epoch`
  // after incrementing: if it moved, our registration raced reclaim() and may already be
  // invisible to it, so undo it and retry under the parity that's current now — reclaim()
  // can't have drained that one yet, since it hasn't started an old-parity wait for it.
  EpochToken(std::array<EpochSlot, 2> &slots, std::atomic<uint64_t> &epoch, EpochRole role)
      : slots_(slots), role_(role) {
    for (;;) {
      parity_ = epoch.load(std::memory_order_acquire) & 1;
      counter().fetch_add(1, std::memory_order_acq_rel);
      if ((epoch.load(std::memory_order_acquire) & 1) == parity_) {
        break;
      }
      counter().fetch_sub(1, std::memory_order_acq_rel);
    }
  }
  ~EpochToken() { counter().fetch_sub(1, std::memory_order_acq_rel); }
  EpochToken(const EpochToken &) = delete;
  auto operator=(const EpochToken &) -> EpochToken & = delete;

 private:
  [[nodiscard]] auto counter() -> std::atomic<int64_t> & {
    return role_ == EpochRole::kReader ? slots_[parity_].readers : slots_[parity_].writers;
  }

  std::array<EpochSlot, 2> &slots_;
  EpochRole role_;
  uint64_t parity_;
};

}  // namespace pskiplist

#include <cstdint>
#include <functional>
#include <random>
#include <thread>

namespace pskiplist {

inline constexpr double kDefaultLevelPromotionProbability = 0.25;
inline constexpr int kDefaultMaxLevel = 32;

// Assigns each new node's participation height via a geometric distribution (2.5節):
// starting at level 1, promotes to the next level with probability `p` until it stops or
// reaches `max_level`. RNG state is thread-local, seeded once per thread from `seed`
// combined with the calling thread's id — concurrent callers never synchronize on a
// shared generator, and a fixed `seed` gives a reproducible sequence for single-threaded
// use (6章's fault-injection tests), without claiming exact reproducibility across
// concurrent interleavings.
class LevelGenerator {
 public:
  explicit LevelGenerator(uint64_t seed, int max_level = kDefaultMaxLevel, double p = kDefaultLevelPromotionProbability)
      : seed_(seed), max_level_(max_level), p_(p) {}

  [[nodiscard]] auto next_level() const -> int {
    thread_local std::mt19937_64 rng(seed_ ^ std::hash<std::thread::id>{}(std::this_thread::get_id()));
    std::uniform_real_distribution<double> unit(0.0, 1.0);
    int level = 1;
    while (level < max_level_ && unit(rng) < p_) {
      ++level;
    }
    return level;
  }

 private:
  uint64_t seed_;
  int max_level_;
  double p_;
};

}  // namespace pskiplist

#include <fcntl.h>
#include <unistd.h>

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <optional>
#include <system_error>

namespace pskiplist {

inline constexpr uint32_t kManifestMagic = 0x504b4c31;  // "PKL1"
inline constexpr uint8_t kManifestFormatVersion = 1;

// 32B fixed manifest header (3章). A mismatched format_version is treated identically to
// a missing manifest — no migration is implemented.
struct ManifestHeader {
  uint32_t magic = kManifestMagic;
  uint8_t format_version = kManifestFormatVersion;
  uint8_t reserved[3] = {};
  uint64_t epoch = 0;            // node epoch stamps <= this are trusted as durable
  uint64_t high_water_mark = 0;  // bump allocation's last reached offset
  uint64_t checksum = 0;         // FNV-1a64 of this header with checksum itself zeroed
};
static_assert(sizeof(ManifestHeader) == 32);

[[nodiscard]] inline auto manifest_checksum(const ManifestHeader &header) -> uint64_t {
  ManifestHeader zeroed = header;
  zeroed.checksum = 0;
  const auto *bytes = reinterpret_cast<const unsigned char *>(&zeroed);
  uint64_t hash = 0xcbf29ce484222325ULL;
  for (size_t i = 0; i < sizeof(zeroed); ++i) {
    hash ^= bytes[i];
    hash *= 0x100000001b3ULL;
  }
  return hash;
}

[[nodiscard]] inline auto manifest_path(const std::filesystem::path &data_path) -> std::filesystem::path {
  auto path = data_path;
  path += ".manifest";
  return path;
}

// Writes the manifest for `data_path` via temp file + fsync + atomic rename (3章), so a
// reader never observes a partially-written manifest.
inline void write_manifest(const std::filesystem::path &data_path, uint64_t epoch, uint64_t high_water_mark) {
  ManifestHeader header;
  header.epoch = epoch;
  header.high_water_mark = high_water_mark;
  header.checksum = manifest_checksum(header);

  const auto final_path = manifest_path(data_path);
  auto tmp_path = final_path;
  tmp_path += ".tmp";

  const int fd = ::open(tmp_path.c_str(), O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if (fd < 0) {
    throw std::system_error(errno, std::generic_category(), "open(" + tmp_path.string() + ")");
  }
  const ssize_t written = ::write(fd, &header, sizeof(header));
  if (written != static_cast<ssize_t>(sizeof(header))) {
    const int err = errno;
    ::close(fd);
    throw std::system_error(err, std::generic_category(), "write(" + tmp_path.string() + ")");
  }
  if (::fsync(fd) != 0) {
    const int err = errno;
    ::close(fd);
    throw std::system_error(err, std::generic_category(), "fsync(" + tmp_path.string() + ")");
  }
  ::close(fd);

  std::error_code ec;
  std::filesystem::rename(tmp_path, final_path, ec);
  if (ec) {
    throw std::system_error(ec, "rename(" + tmp_path.string() + " -> " + final_path.string() + ")");
  }
}

// Returns nullopt if the manifest is missing, truncated, has a mismatched magic or
// format_version, or fails its checksum — any of these are treated as "no checkpoint has
// ever completed for this file".
[[nodiscard]] inline auto read_manifest(const std::filesystem::path &data_path) -> std::optional<ManifestHeader> {
  const auto path = manifest_path(data_path);
  const int fd = ::open(path.c_str(), O_RDONLY);
  if (fd < 0) return std::nullopt;

  ManifestHeader header{};
  const ssize_t bytes_read = ::read(fd, &header, sizeof(header));
  ::close(fd);
  if (bytes_read != static_cast<ssize_t>(sizeof(header))) return std::nullopt;
  if (header.magic != kManifestMagic) return std::nullopt;
  if (header.format_version != kManifestFormatVersion) return std::nullopt;
  if (manifest_checksum(header) != header.checksum) return std::nullopt;

  return header;
}

}  // namespace pskiplist

#include <atomic>
#include <cstdint>

namespace pskiplist {

// A generic lock-free "find, helping to unlink any marked node along the way" search over a
// singly-linked list whose nodes are addressed by `Identity` (an Offset into a fixed array
// for Level 0, or a raw pointer for an upper level — see marked_offset.hpp / marked_pointer.hpp)
// and whose per-node "next" pointer is packed together with a deletion mark bit into one
// atomic<uint64_t> word (Traits::pack/value/is_marked). This is the one idea both layers
// share: a single CAS on a predecessor's word simultaneously validates "the successor is
// still what I read" and "the predecessor itself hasn't been marked out from under me",
// because both facts live in the same word.
//
// `start_id`/`start_word` is where the walk begins — typically a caller-supplied search hint
// pointing past most of the list. If that word turns out to already be marked, its offset/
// pointer bits can no longer be trusted at all (they may already have been repurposed for a
// pending-reclaim queue by the time this reads them), so the walk restarts from
// `fallback_id`/`fallback_word` instead — a caller-guaranteed-live anchor (a list head) —
// rather than retrying the same possibly-permanently-marked start forever. Callers with no
// meaningful hint (Level N's per-level searches always start at a list head, which is never
// itself deleted) just pass the same id/word twice; the fallback path is then unreachable,
// not merely harmless.
//
// `is_dead` is a second, independent deletion signal a node can carry *outside* its own
// word — Level N has no per-node source of truth of its own (an UpperNode is nothing but a
// search hint), so it borrows Level 0's tombstone state via this hook instead of maintaining
// a redundant one; Level 0 has no such external signal, so it always passes a hook that
// returns false. A node flagged dead this way but not yet structurally marked gets marked
// right here (idempotent — a no-op if a concurrent caller already did) before falling into
// the same help-splice-and-restart path as a node found already marked, so a zombie gets
// caught by whichever search encounters it first, however late.
//
// On encountering a node whose own word is marked, this helps splice it out via one CAS on
// its predecessor's word and, if that CAS wins, reports the removed identity via `on_splice`
// — then restarts the whole walk from the start (not fallback), since the predecessor used up
// to that point can no longer be trusted. Stops and returns the first node whose key is not
// less than `key`, or Traits::null_id() if the list runs out first; `*out_pred` receives that
// result's immediate predecessor.
template <typename Identity,
          typename Traits,
          typename Key,
          typename Less,
          typename NextWordFn,
          typename KeyFn,
          typename IsDeadFn,
          typename OnSpliceFn>
[[nodiscard]] auto marked_list_find(Identity start_id,
                                    std::atomic<uint64_t> &start_word,
                                    Identity fallback_id,
                                    std::atomic<uint64_t> &fallback_word,
                                    const Key &key,
                                    Less less,
                                    NextWordFn next_word,
                                    KeyFn key_of,
                                    IsDeadFn is_dead,
                                    OnSpliceFn on_splice,
                                    Identity *out_pred) -> Identity {
  Identity anchor_id = start_id;
  std::atomic<uint64_t> *anchor_word = &start_word;
  for (;;) {
    Identity pred = anchor_id;
    std::atomic<uint64_t> *pred_word = anchor_word;
    const uint64_t pred_raw = pred_word->load(std::memory_order_acquire);
    if (Traits::is_marked(pred_raw)) {
      anchor_id = fallback_id;
      anchor_word = &fallback_word;
      continue;
    }
    Identity current = Traits::value(pred_raw);
    for (;;) {
      if (current == Traits::null_id()) {
        *out_pred = pred;
        return current;
      }
      uint64_t current_raw = next_word(current).load(std::memory_order_acquire);
      if (!Traits::is_marked(current_raw) && is_dead(current)) {
        marked_list_mark_for_deletion<Identity, Traits>(current, next_word);
        current_raw = next_word(current).load(std::memory_order_acquire);
      }
      if (Traits::is_marked(current_raw)) {
        const Identity successor = Traits::value(current_raw);
        uint64_t expected = Traits::pack(current, false);
        const uint64_t desired = Traits::pack(successor, false);
        if (pred_word->compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
          on_splice(current);
        }
        break;  // restart the whole walk from anchor_id/anchor_word — pred_word may now be stale
      }
      if (!less(key_of(current), key)) {
        *out_pred = pred;
        return current;
      }
      pred = current;
      pred_word = &next_word(current);
      current = Traits::value(current_raw);
    }
  }
}

// Marks `id`'s own word for logical deletion, preserving whatever successor it currently
// names — the first half of removing a node, done once before any splice is attempted.
// Retries against concurrent inserts that change the successor while leaving mark unset;
// a no-op (mark already set) if another thread got there first.
template <typename Identity, typename Traits, typename OwnWordFn>
void marked_list_mark_for_deletion(Identity id, OwnWordFn own_word) {
  uint64_t raw = own_word(id).load(std::memory_order_acquire);
  while (!Traits::is_marked(raw)) {
    const uint64_t desired = Traits::pack(Traits::value(raw), true);
    if (own_word(id).compare_exchange_strong(raw, desired, std::memory_order_acq_rel)) {
      break;
    }
  }
}

// A plain lock-free Treiber stack push: `value` becomes the new head, linked to the old one
// by `set_next(value, old_head)` — usually a direct store into `value`'s own dedicated "next"
// word, but left as a callback rather than a word reference so a caller that repurposes an
// existing word (packing in a mark bit, say) can do that instead. No pop is provided — every
// user of this drains the whole stack at once via `head.exchange(...,
// std::memory_order_acq_rel)` rather than popping items one at a time, so there's no ABA
// hazard to guard against (unlike a free list, which needs marked_offset.hpp's tagged
// pointer instead).
template <typename Identity, typename SetNextFn>
void stack_push(std::atomic<Identity> &head, Identity value, SetNextFn set_next) {
  Identity old_head = head.load(std::memory_order_relaxed);
  do {
    set_next(value, old_head);
  } while (!head.compare_exchange_weak(old_head, value, std::memory_order_acq_rel, std::memory_order_relaxed));
}

}  // namespace pskiplist

#include <cstdint>

namespace pskiplist {

// Marks the low bit of a pointer to signal logical deletion — the same idea as
// marked_offset.hpp's kForwardMarkBit for Offset, just applied to a pointer's bit 0 instead
// of Offset's bit 63. Safe because every allocator this project uses (`::operator new`)
// returns addresses aligned well beyond 2 bytes, so bit 0 of a live pointer is always 0.
template <typename T>
[[nodiscard]] inline auto pack_marked_ptr(T *ptr, bool marked) -> uintptr_t {
  const auto value = reinterpret_cast<uintptr_t>(ptr);
  return marked ? (value | uintptr_t{1}) : value;
}

template <typename T>
[[nodiscard]] inline auto marked_ptr_value(uintptr_t raw) -> T * {
  return reinterpret_cast<T *>(raw & ~uintptr_t{1});
}

[[nodiscard]] inline auto marked_ptr_marked(uintptr_t raw) -> bool { return (raw & uintptr_t{1}) != 0; }

// Traits for marked_list.hpp's generic algorithms, binding them to pointer identities.
// null_id() is nullptr — a pointer-based list's natural "no next" sentinel, unlike Level 0's
// offset-based list where that role is played by a real node (kTail).
template <typename T>
struct PointerMarkedTraits {
  static auto pack(T *id, bool marked) -> uint64_t { return pack_marked_ptr<T>(id, marked); }
  static auto value(uint64_t raw) -> T * { return marked_ptr_value<T>(raw); }
  static auto is_marked(uint64_t raw) -> bool { return marked_ptr_marked(raw); }
  static auto null_id() -> T * { return nullptr; }
};

}  // namespace pskiplist

#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cstddef>
#include <filesystem>
#include <stdexcept>
#include <system_error>

namespace pskiplist {

// RAII POSIX file opened, sized, and mapped MAP_SHARED for direct in-place mutation.
// Sized once at construction and never grown (2.6節). A brand-new (empty) file is
// zero-extended to size_bytes; an existing non-empty file's content is preserved as-is
// (recovery, 3章, decides what in it to trust) and must already be exactly size_bytes —
// a mismatch is a construction error, not something this class silently resolves.
class MmapFile {
 public:
  MmapFile(const std::filesystem::path &path, size_t size_bytes) : size_(size_bytes) {
    fd_ = ::open(path.c_str(), O_RDWR | O_CREAT, 0644);
    if (fd_ < 0) {
      throw std::system_error(errno, std::generic_category(), "open(" + path.string() + ")");
    }

    struct stat st {};
    if (::fstat(fd_, &st) != 0) {
      const int err = errno;
      ::close(fd_);
      throw std::system_error(err, std::generic_category(), "fstat(" + path.string() + ")");
    }

    if (st.st_size == 0) {
      if (::ftruncate(fd_, static_cast<off_t>(size_)) != 0) {
        const int err = errno;
        ::close(fd_);
        throw std::system_error(err, std::generic_category(), "ftruncate(" + path.string() + ")");
      }
    } else {
      reused_ = true;
      if (static_cast<size_t>(st.st_size) != size_) {
        ::close(fd_);
        throw std::invalid_argument("pskiplist: " + path.string() +
                                    " exists with a size that does not match capacity_bytes");
      }
    }

    data_ = ::mmap(nullptr, size_, PROT_READ | PROT_WRITE, MAP_SHARED, fd_, 0);
    if (data_ == MAP_FAILED) {
      const int err = errno;
      ::close(fd_);
      throw std::system_error(err, std::generic_category(), "mmap(" + path.string() + ")");
    }
  }

  ~MmapFile() {
    if (data_ != nullptr && data_ != MAP_FAILED) {
      ::munmap(data_, size_);
    }
    if (fd_ >= 0) {
      ::close(fd_);
    }
  }

  MmapFile(const MmapFile &) = delete;
  auto operator=(const MmapFile &) -> MmapFile & = delete;

  [[nodiscard]] auto data() const -> void * { return data_; }
  [[nodiscard]] auto size() const -> size_t { return size_; }
  // True if `path` already existed with content (i.e. wasn't freshly created) —
  // PSkipList uses this to decide whether to run recovery instead of a fresh init.
  [[nodiscard]] auto reused() const -> bool { return reused_; }

  // Blocks until the mapping's dirty pages are durable on the underlying storage (3章).
  void sync() const {
    if (::msync(data_, size_, MS_SYNC) != 0) {
      throw std::system_error(errno, std::generic_category(), "msync");
    }
  }

 private:
  int fd_ = -1;
  void *data_ = nullptr;
  size_t size_ = 0;
  bool reused_ = false;
};

}  // namespace pskiplist

#include <cstdint>

namespace pskiplist {

enum class NodeState : uint8_t {
  kLive = 0,
  kTombstonedLinked = 1,
  kTombstonedUnlinked = 2,
};

class PackedValue {
 public:
  PackedValue() = default;
  explicit PackedValue(uint64_t bits) : bits_(bits) {}
  static auto live(uint64_t payload) -> PackedValue { return PackedValue(encode(NodeState::kLive, payload)); }

  [[nodiscard]] auto state() const -> NodeState { return static_cast<NodeState>(bits_ >> kPayloadBits); }
  [[nodiscard]] auto payload() const -> uint64_t { return bits_ & kPayloadMask; }
  [[nodiscard]] auto raw() const -> uint64_t { return bits_; }
  [[nodiscard]] auto with_state(NodeState state) const -> PackedValue { return PackedValue(encode(state, payload())); }

  static constexpr int kPayloadBits = 62;
  static constexpr uint64_t kPayloadMask = (uint64_t{1} << kPayloadBits) - 1;

 private:
  static auto encode(NodeState state, uint64_t payload) -> uint64_t {
    return (static_cast<uint64_t>(state) << kPayloadBits) | (payload & kPayloadMask);
  }
  uint64_t bits_ = 0;
};

}  // namespace pskiplist

#include <array>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <mutex>
#include <new>
#include <optional>
#include <random>
#include <stdexcept>
#include <thread>
#include <vector>

#include <atomic>
#include <cstddef>
#include <new>

namespace pskiplist {

// A single volatile, DRAM-only skip-list node participating in levels 1..height (2.4節).
// Its forward pointers for all `height` levels are allocated as one contiguous block
// following the header rather than as `height` separate allocations (8章), so a search
// descending through this node's levels stays in one cache-line neighborhood. Only ever
// constructed via allocate_upper_node() below, which owns the combined allocation.
//
// Each `forwards[level]` packs (successor pointer, mark bit) into one atomic<uint64_t> via
// marked_pointer.hpp — the same idea as Level 0's forward0 (marked_offset.hpp), letting a
// single CAS on a predecessor's word validate both "the successor is still what I read" and
// "the predecessor itself hasn't been marked out from under me" (see marked_list.hpp).
//
// `levels_remaining` counts down from `height` as each level's splice completes (marked_list.hpp's
// on_splice callback); whoever brings it to 0 knows this node is gone from every list it
// participated in and is the one who enqueues it for EBR reclaim (reclaim() in skiplist.hpp).
//
// `next_pending` is a dedicated field for that reclaim queue rather than reusing forwards[0]:
// keeping it separate avoids coupling reclaim-queue linkage to level 1 specifically being the
// last level spliced, which the levels_remaining counter alone doesn't guarantee ordering-wise.
struct UpperNode {
  Offset durable_offset;
  int height;
  std::atomic<int> levels_remaining{0};
  std::atomic<UpperNode *> next_pending{nullptr};
  std::atomic<uint64_t> forwards[1];  // actually `height` entries — see allocate_upper_node()
};

[[nodiscard]] inline auto allocate_upper_node(Offset durable_offset, int height) -> UpperNode * {
  void *memory = ::operator new(sizeof(UpperNode) + sizeof(std::atomic<uint64_t>) * static_cast<size_t>(height - 1));
  auto *node = static_cast<UpperNode *>(memory);
  ::new (&node->durable_offset) Offset(durable_offset);
  ::new (&node->height) int(height);
  ::new (&node->levels_remaining) std::atomic<int>(height);
  ::new (&node->next_pending) std::atomic<UpperNode *>(nullptr);
  for (int level = 0; level < height; ++level) {
    ::new (&node->forwards[level]) std::atomic<uint64_t>(pack_marked_ptr<UpperNode>(nullptr, false));
  }
  return node;
}

inline void deallocate_upper_node(UpperNode *node) {
  node->next_pending.~atomic();
  node->levels_remaining.~atomic();
  for (int level = 0; level < node->height; ++level) {
    node->forwards[level].~atomic();
  }
  ::operator delete(node);
}

}  // namespace pskiplist

namespace pskiplist {

template <typename Key, typename Compare = std::less<Key>>
  requires SkipListKey<Key> && SkipListCompare<Compare, Key>
class PSkipList {
 public:
  // `capacity_bytes` is fixed for the lifetime of the mapping (2.6節) — sized generously
  // up front, since a sparse file only consumes disk for pages actually written. The data
  // file at `path` is mutated in place via MAP_SHARED; it is not rewritten on checkpoint.
  explicit PSkipList(const std::filesystem::path &path, size_t capacity_bytes)
      : path_(path),
        file_(path, capacity_bytes),
        nodes_(static_cast<DurableNode<Key> *>(file_.data())),
        capacity_slots_(file_.size() / sizeof(DurableNode<Key>)),
        level_generator_(std::random_device{}()) {
    if (capacity_slots_ < 2) {
      throw std::invalid_argument("pskiplist: capacity_bytes too small to hold head/tail sentinels");
    }
    if (capacity_slots_ > kMaxTaggedOffset) {
      throw std::invalid_argument("pskiplist: capacity_bytes exceeds the maximum representable node count");
    }
    if (file_.reused()) {
      recover();
    } else {
      initialize_fresh();
    }
  }

  // The upper levels (2.4節) are plain heap objects with no owning smart pointer, so they
  // need explicit cleanup. Single-threaded, like the rest of destruction (5章) — the
  // caller guarantees no concurrent access by this point, so no EBR is needed here.
  ~PSkipList() {
    UpperNode *current = marked_ptr_value<UpperNode>(upper_heads_[0].load(std::memory_order_relaxed));
    while (current != nullptr) {
      UpperNode *next = marked_ptr_value<UpperNode>(current->forwards[0].load(std::memory_order_relaxed));
      deallocate_upper_node(current);
      current = next;
    }
    UpperNode *pending = pending_upper_deletes_.load(std::memory_order_relaxed);
    while (pending != nullptr) {
      UpperNode *next = pending->next_pending.load(std::memory_order_relaxed);
      deallocate_upper_node(pending);
      pending = next;
    }
  }

  PSkipList(const PSkipList &) = delete;
  auto operator=(const PSkipList &) -> PSkipList & = delete;

  [[nodiscard]] auto get(const Key &key) const -> std::optional<uint64_t> {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kReader);
    Offset predecessor = kNullOffset;
    const Offset current = find_at_or_after(key, &predecessor, search_upper_levels(key).level0_hint);
    if (current == kNullOffset || current == kTail || !keys_equal(nodes_[current].key, key)) {
      return std::nullopt;
    }
    const PackedValue v(nodes_[current].value.load(std::memory_order_acquire));
    if (v.state() != NodeState::kLive) return std::nullopt;
    return v.payload();
  }

  [[nodiscard]] auto put(const Key &key, uint64_t payload) -> bool {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kWriter);
    const Offset hint = search_upper_levels(key).level0_hint;
    Offset fresh = kNullOffset;
    for (;;) {
      Offset predecessor = kNullOffset;
      const Offset existing = find_at_or_after(key, &predecessor, hint);
      if (existing != kNullOffset && existing != kTail && keys_equal(nodes_[existing].key, key)) {
        uint64_t expected = nodes_[existing].value.load(std::memory_order_acquire);
        if (PackedValue(expected).state() == NodeState::kTombstonedUnlinked) {
          std::this_thread::yield();
          continue;
        }
        shadow_if_first_touch_since_checkpoint(existing, expected);
        const uint64_t desired = PackedValue::live(payload).raw();
        if (nodes_[existing].value.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
          return true;
        }
        continue;
      }

      if (fresh == kNullOffset) {
        fresh = allocate();
        if (fresh == kNullOffset) return false;
        nodes_[fresh].key = key;
        nodes_[fresh].value.store(PackedValue::live(payload).raw(), std::memory_order_relaxed);
        nodes_[fresh].epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_relaxed);
        // A recycled slot may still carry a previous occupant's shadow — reset it to avoid
        // any stale-data confusion, even though mutation_epoch (set fresh below) is what
        // actually gates whether recover() ever looks at it.
        nodes_[fresh].checkpointed_value.store(0, std::memory_order_relaxed);
        nodes_[fresh].mutation_epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_relaxed);
      }
      nodes_[fresh].forward0.store(pack_forward(existing, false), std::memory_order_relaxed);

      uint64_t expected_next = pack_forward(existing, false);
      const uint64_t desired_next = pack_forward(fresh, false);
      if (nodes_[predecessor].forward0.compare_exchange_strong(
              expected_next, desired_next, std::memory_order_acq_rel)) {
        link_upper_levels(fresh, key, level_generator_.next_level());
        return true;
      }
    }
  }

  [[nodiscard]] auto remove(const Key &key) -> bool {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kWriter);
    Offset predecessor = kNullOffset;
    const Offset current = find_at_or_after(key, &predecessor, search_upper_levels(key).level0_hint);
    if (current == kNullOffset || current == kTail || !keys_equal(nodes_[current].key, key)) return false;

    for (;;) {
      uint64_t expected = nodes_[current].value.load(std::memory_order_acquire);
      const PackedValue v(expected);
      if (v.state() != NodeState::kLive) return false;
      shadow_if_first_touch_since_checkpoint(current, expected);
      const uint64_t desired = v.with_state(NodeState::kTombstonedLinked).raw();
      if (nodes_[current].value.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
        break;
      }
    }

    unlink_upper_levels(key, current);  // upper levels are never persisted — no crash-safety concern
    // Physical unlink (splice + slot reuse) waits for checkpoint() rather than happening now
    // — reusing the slot before the removal is durably checkpointed would destroy data a
    // crash-then-recover should still be able to fall back to.
    enqueue_pending_checkpoint_unlink(current);
    return true;
  }

  template <typename Callback>
  void scan(const Key &begin, const Key &end, Callback &&callback) const {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kReader);
    Offset predecessor = kNullOffset;
    Offset current = find_at_or_after(begin, &predecessor, search_upper_levels(begin).level0_hint);
    while (current != kNullOffset && current != kTail) {
      const auto &node = nodes_[current];
      if (!less_(node.key, end)) break;
      const PackedValue v(node.value.load(std::memory_order_acquire));
      if (v.state() == NodeState::kLive) {
        callback(node.key, v.payload());
      }
      current = forward_offset(node.forward0.load(std::memory_order_acquire));
    }
  }

  void reclaim() {
    const std::lock_guard<std::mutex> epoch_lock(epoch_mutex_);

    // Take exclusive ownership of every offset currently pending unlink; nothing else
    // will touch these nodes' forward0 links until free_push() below repurposes them.
    Offset pending_head = drain_pending_unlinks();
    UpperNode *pending_upper = pending_upper_deletes_.exchange(nullptr, std::memory_order_acq_rel);

    // Physical-reclaim safety needs every possible holder of a stale offset — reader or
    // writer — to have drained, unlike checkpoint()'s writer-only wait (3章).
    const uint64_t old_parity = epoch_.load(std::memory_order_acquire) & 1;
    epoch_.fetch_add(1, std::memory_order_acq_rel);
    auto &old_slot = epoch_slots_[old_parity];
    while (old_slot.readers.load(std::memory_order_acquire) != 0 ||
           old_slot.writers.load(std::memory_order_acquire) != 0) {
      std::this_thread::yield();
    }

    while (pending_head != kNullOffset) {
      const Offset next = forward_offset(nodes_[pending_head].forward0.load(std::memory_order_relaxed));
      free_push(pending_head);
      pending_head = next;
    }

    while (pending_upper != nullptr) {
      UpperNode *next = pending_upper->next_pending.load(std::memory_order_relaxed);
      deallocate_upper_node(pending_upper);
      pending_upper = next;
    }
  }

  // Synchronous and blocking. Any put()/remove() that had already returned before this
  // call started is durable once this returns true; whether one that started during the
  // call is durable is unspecified. Concurrent checkpoint() calls are serialized on
  // epoch_mutex_. Only writers are waited for — a long-running scan() never blocks this.
  [[nodiscard]] auto checkpoint() -> bool {
    const std::lock_guard<std::mutex> epoch_lock(epoch_mutex_);

    // Snapshot before the epoch bump (same idiom as reclaim()'s drain_pending_unlinks): the
    // writer-wait below guarantees everything captured here happened-before the manifest
    // about to be published, so it's all safe to physically unlink once that's done.
    Offset pending_unlink = pending_checkpoint_unlink_.exchange(kNullOffset, std::memory_order_acq_rel);

    const uint64_t published_epoch = epoch_.load(std::memory_order_acquire);
    epoch_.fetch_add(1, std::memory_order_acq_rel);
    auto &old_slot = epoch_slots_[published_epoch & 1];
    while (old_slot.writers.load(std::memory_order_acquire) != 0) {
      std::this_thread::yield();
    }

    file_.sync();
    write_manifest(path_, published_epoch, high_water_mark_.load(std::memory_order_acquire));
    // Only after the manifest is durably published — otherwise a concurrent put()/remove()
    // could see "already checkpointed" before that's true and skip a shadow recover() needs.
    last_published_epoch_.store(published_epoch, std::memory_order_release);

    // physically_unlink_best_effort() is unchanged and already tolerates redundant calls, so
    // resetting the queued flag before (not after) calling it is safe even if a concurrent
    // resurrect-then-remove immediately re-queues the same offset.
    while (pending_unlink != kNullOffset) {
      const Offset next = nodes_[pending_unlink].next_checkpoint_unlink.load(std::memory_order_relaxed);
      nodes_[pending_unlink].pending_checkpoint_unlink_queued.store(false, std::memory_order_release);
      physically_unlink_best_effort(nodes_[pending_unlink].key, pending_unlink);
      pending_unlink = next;
    }
    return true;
  }

 private:
  static constexpr Offset kHead = 0;
  static constexpr Offset kTail = 1;

  // Traits for marked_list.hpp's generic algorithms, binding them to Offset identities and
  // Level 0's existing (offset, mark bit) packing (marked_offset.hpp) unchanged.
  struct OffsetMarkedTraits {
    static constexpr auto pack(Offset id, bool marked) -> uint64_t { return pack_forward(id, marked); }
    static constexpr auto value(uint64_t raw) -> Offset { return forward_offset(raw); }
    static constexpr auto is_marked(uint64_t raw) -> bool { return forward_marked(raw); }
    static constexpr auto null_id() -> Offset { return kTail; }
  };

  void initialize_fresh() {
    ::new (&nodes_[kHead]) DurableNode<Key>();
    ::new (&nodes_[kTail]) DurableNode<Key>();
    nodes_[kHead].forward0.store(pack_forward(kTail, false), std::memory_order_relaxed);
  }

  // Called only when the backing file already had content. No manifest means no
  // checkpoint() ever completed for this file, so nothing in it is trusted — start fresh
  // exactly as a brand-new file would. Otherwise, walk Level 0 from head, trusting nodes
  // in encounter order only while their epoch stamp is <= the manifest's: a node past
  // that point may have been concurrently written by a writer checkpoint() didn't wait
  // for, so neither it nor anything reachable only through it is trustworthy, and the
  // walk stops there, splicing the chain to end at that point. Every allocated slot
  // (2章) below the manifest's high_water_mark that the walk didn't reach — whether never
  // linked in, or unlinked-but-not-yet-reclaimed before the crash — becomes free (2.3節's
  // mark-and-sweep). high_water_mark_ rolls back to the manifest's value: any allocation
  // racing the checkpoint that isn't captured by it is simply not recovered.
  void recover() {
    const auto manifest = read_manifest(path_);
    if (!manifest.has_value()) {
      initialize_fresh();
      return;
    }

    const uint64_t threshold = manifest->epoch;
    const uint64_t recovered_high_water_mark = manifest->high_water_mark;

    // epoch_ is a per-process counter, not persisted, and restarts at 0 on every reopen.
    // Left unseeded, this session's checkpoints would publish epoch numbers below the
    // previous session's, and a later recovery would then wrongly trim nodes this session
    // already checkpointed (their epoch stamps would look "too new" against that lower
    // threshold). Resume from threshold + 1 to keep numbering monotonic across restarts.
    epoch_.store(threshold + 1, std::memory_order_relaxed);
    // Same reasoning as epoch_ above — shadow_if_first_touch_since_checkpoint() compares a
    // node's mutation_epoch against this to decide whether it's already shadowed.
    last_published_epoch_.store(threshold, std::memory_order_relaxed);

    std::vector<bool> reached(recovered_high_water_mark, false);
    Offset pred = kHead;
    Offset current = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (current != kTail) {
      if (current >= recovered_high_water_mark || nodes_[current].epoch.load(std::memory_order_relaxed) > threshold) {
        nodes_[pred].forward0.store(pack_forward(kTail, false), std::memory_order_relaxed);
        break;
      }
      // Existence is trusted (creation epoch <= threshold above), but the latest mutation —
      // put() or remove(), shadow_if_first_touch_since_checkpoint() doesn't distinguish —
      // might not be; revert to the shadow, which always holds the last-checkpointed value.
      if (nodes_[current].mutation_epoch.load(std::memory_order_relaxed) > threshold) {
        nodes_[current].value.store(nodes_[current].checkpointed_value.load(std::memory_order_relaxed),
                                    std::memory_order_relaxed);
        nodes_[current].mutation_epoch.store(threshold, std::memory_order_relaxed);
      }
      reached[current] = true;
      pred = current;
      current = forward_offset(nodes_[current].forward0.load(std::memory_order_relaxed));
    }

    free_head_.store(0, std::memory_order_relaxed);
    for (Offset offset = 2; offset < recovered_high_water_mark; ++offset) {
      if (!reached[offset]) {
        free_push(offset);
      }
    }

    high_water_mark_.store(recovered_high_water_mark, std::memory_order_relaxed);

    // A crash between checkpoint()'s manifest write and its (in-memory, so lost) drain of
    // pending_checkpoint_unlink_ can leave a checkpointed removal (mutation_epoch <=
    // threshold, so not reverted above) still TombstonedLinked and reachable — nothing at
    // runtime will ever retry it, since remove() only enqueues on a fresh Live->Tombstoned
    // transition. Complete it now (recovery is single-threaded, so this is safe) in its own
    // pass rather than folded into the walk above — physically_unlink_best_effort()'s own
    // find_at_or_after() splice would otherwise corrupt that walk's pred/current bookkeeping.
    Offset walk = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (walk != kTail) {
      const Offset next = forward_offset(nodes_[walk].forward0.load(std::memory_order_relaxed));
      if (PackedValue(nodes_[walk].value.load(std::memory_order_relaxed)).state() == NodeState::kTombstonedLinked) {
        physically_unlink_best_effort(nodes_[walk].key, walk);
      }
      walk = next;
    }

    rebuild_upper_levels();
  }

  // The upper levels are pure DRAM search hints (2.4節) — never persisted, so a process
  // restart always starts them empty and rebuilds by walking the now-trusted Level 0 chain
  // above, re-rolling each surviving node's height exactly as put() would for a fresh
  // insert. Single-threaded (the constructor's caller guarantees no concurrent access yet,
  // matching the destructor's assumption), so link_upper_levels's CAS retries are all
  // uncontended — this is O(corpus) as noted in 7章's open-questions list, unavoidable
  // without persisting the upper levels themselves (which 2.4節 deliberately avoids).
  void rebuild_upper_levels() {
    Offset current = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (current != kTail) {
      link_upper_levels(current, nodes_[current].key, level_generator_.next_level());
      current = forward_offset(nodes_[current].forward0.load(std::memory_order_relaxed));
    }
  }

  [[nodiscard]] auto keys_equal(const Key &a, const Key &b) const -> bool { return !less_(a, b) && !less_(b, a); }

  // Shared by put()'s existing-key branch and remove()'s tombstone transition — both are
  // in-place mutations to a node that may already be checkpointed. `expected_live_value` is
  // whatever the caller already read for its own CAS attempt, not re-read here, so the shadow
  // and the CAS always agree on what "before" looked like. Only shadows on the first touch
  // since the last checkpoint: once mutation_epoch is ahead of last_published_epoch_, an
  // earlier mutation in this same window already captured the value recover() needs.
  void shadow_if_first_touch_since_checkpoint(Offset offset, uint64_t expected_live_value) const {
    if (nodes_[offset].mutation_epoch.load(std::memory_order_acquire) <=
        last_published_epoch_.load(std::memory_order_acquire)) {
      nodes_[offset].checkpointed_value.store(expected_live_value, std::memory_order_relaxed);
      nodes_[offset].mutation_epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_release);
    }
  }

  // Traverses to the first node with key >= `key`, helping to physically unlink any
  // marked (logically deleted) node it encounters along the way (4.2節). A helping CAS
  // that wins pushes the unlinked node to the pending-unlink queue; on any CAS outcome
  // touching a marked node the whole search restarts from head, since a stale predecessor
  // can no longer be trusted.
  //
  // `hint` seeds the first attempt's starting point instead of kHead — typically a
  // predecessor found via the upper levels (2.4節), letting this skip most of the Level 0
  // scan. A hint's key is safe to trust as < `key` forever (keys never change once set),
  // but it must be re-verified as still unmarked immediately before use: if it's since
  // been unlinked, its forward0 no longer means "live successor" (4.2節), and any retry
  // (from a restart below) always falls back to kHead.
  [[nodiscard]] auto find_at_or_after(const Key &key, Offset *predecessor, Offset hint = kHead) const -> Offset {
    return marked_list_find<Offset, OffsetMarkedTraits>(
        hint,
        nodes_[hint].forward0,
        kHead,
        nodes_[kHead].forward0,
        key,
        less_,
        [this](Offset o) -> std::atomic<uint64_t> & { return nodes_[o].forward0; },
        [this](Offset o) -> const Key & { return nodes_[o].key; },
        [](Offset) { return false; },
        [this](Offset o) { enqueue_pending_unlink(o); },
        predecessor);
  }

  // Lock-free multi-producer stack: any number of unlinkers push concurrently, and
  // reclaim() drains the whole thing with a single atomic exchange. There's no per-item
  // pop here, so there's no ABA hazard to guard against — unlike the free list below.
  void enqueue_pending_unlink(Offset offset) const {
    stack_push(pending_head_, offset, [this](Offset o, Offset next) {
      // Keep the mark bit set: this word is already frozen against any stale unmarked-
      // expecting CAS from a thread that read this node before it was ever removed (4.2節)
      // — clearing it here would let such a CAS coincidentally match this repurposed
      // "next pending" value and corrupt the chain.
      nodes_[o].forward0.store(pack_forward(next, true), std::memory_order_relaxed);
    });
  }

  [[nodiscard]] auto drain_pending_unlinks() const -> Offset {
    return pending_head_.exchange(kNullOffset, std::memory_order_acq_rel);
  }

  // Lock-free multi-producer stack of offsets awaiting checkpoint-gated physical unlink,
  // linked via their own dedicated next_checkpoint_unlink field — never forward0, which must
  // keep pointing at each node's real successor until checkpoint() confirms it's safe to
  // splice out. Drained only by checkpoint() (same atomic-exchange idiom as
  // drain_pending_unlinks above). A no-op if already queued: put() can resurrect a
  // TombstonedLinked node straight back to Live (4.1節), and a later remove() re-tombstoning
  // it must not push the same offset onto the stack twice.
  void enqueue_pending_checkpoint_unlink(Offset offset) const {
    bool expected_unqueued = false;
    if (!nodes_[offset].pending_checkpoint_unlink_queued.compare_exchange_strong(
            expected_unqueued, true, std::memory_order_acq_rel)) {
      return;
    }
    stack_push(pending_checkpoint_unlink_, offset, [this](Offset o, Offset next) {
      nodes_[o].next_checkpoint_unlink.store(next, std::memory_order_relaxed);
    });
  }

  // Lock-free Treiber stack with a tagged head (marked_offset.hpp) to rule out ABA: a
  // freed node's own forward0 becomes the "next free" link, safe to repurpose since
  // nothing reaches it through the live chain anymore.
  void free_push(Offset offset) {
    uint64_t old_head = free_head_.load(std::memory_order_relaxed);
    for (;;) {
      // Marked for the same reason as enqueue_pending_unlink above.
      nodes_[offset].forward0.store(pack_forward(tagged_offset(old_head), true), std::memory_order_relaxed);
      const uint64_t new_head = pack_tagged(offset, tagged_generation(old_head) + 1);
      if (free_head_.compare_exchange_weak(old_head, new_head, std::memory_order_acq_rel, std::memory_order_relaxed)) {
        return;
      }
    }
  }

  auto free_pop() -> Offset {
    uint64_t old_head = free_head_.load(std::memory_order_acquire);
    for (;;) {
      const Offset offset = tagged_offset(old_head);
      if (offset == 0) return kNullOffset;  // empty: offset 0 (kHead) is never freed
      const Offset next = forward_offset(nodes_[offset].forward0.load(std::memory_order_relaxed));
      const uint64_t new_head = pack_tagged(next, tagged_generation(old_head) + 1);
      if (free_head_.compare_exchange_weak(old_head, new_head, std::memory_order_acq_rel, std::memory_order_relaxed)) {
        return offset;
      }
    }
  }

  auto allocate() -> Offset {
    const Offset reused = free_pop();
    if (reused != kNullOffset) return reused;

    const Offset next = high_water_mark_.fetch_add(1, std::memory_order_relaxed);
    if (next >= capacity_slots_) {
      high_water_mark_.fetch_sub(1, std::memory_order_relaxed);
      return kNullOffset;
    }
    return next;
  }

  void physically_unlink_best_effort(const Key &key, Offset node_offset) {
    uint64_t expected = nodes_[node_offset].value.load(std::memory_order_acquire);
    const PackedValue v(expected);
    if (v.state() != NodeState::kTombstonedLinked) return;
    const uint64_t desired = v.with_state(NodeState::kTombstonedUnlinked).raw();
    if (!nodes_[node_offset].value.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
      return;
    }

    marked_list_mark_for_deletion<Offset, OffsetMarkedTraits>(
        node_offset, [this](Offset o) -> std::atomic<uint64_t> & { return nodes_[o].forward0; });

    Offset predecessor = kNullOffset;
    static_cast<void>(find_at_or_after(key, &predecessor));
  }

  struct UpperSearchResult {
    Offset level0_hint = kHead;
  };

  // The word a predecessor's own successor at `level` lives in — the list head if there is
  // no predecessor, its forwards[] entry otherwise. Every upper-level search/link/unlink
  // deals in exactly this word.
  [[nodiscard]] auto upper_word(UpperNode *pred, int level) const -> std::atomic<uint64_t> & {
    return pred == nullptr ? upper_heads_[level - 1] : pred->forwards[level - 1];
  }

  // Level N has no deletion signal of its own — an UpperNode is nothing but a search hint
  // for a Level 0 record, so "is this entry logically gone" borrows Level 0's own tombstone
  // state directly rather than duplicating it. See marked_list_find's `is_dead` parameter.
  [[nodiscard]] auto is_upper_node_dead(UpperNode *node) const -> bool {
    return PackedValue(nodes_[node->durable_offset].value.load(std::memory_order_acquire)).state() != NodeState::kLive;
  }

  // The other half of an UpperNode's removal: whoever's splice brings levels_remaining to 0
  // has just unlinked it from the last list it participated in, and is the one who hands it
  // to the EBR registry shared with 3章 (a concurrent reader may still be mid-traversal
  // through it). Called from marked_list_find's on_splice hook — for any level, from any
  // thread's search, not just an explicit unlink_upper_levels() call — since a node can be
  // helped off of each of its levels independently and by whoever gets there first.
  void on_upper_splice(UpperNode *node) const {
    if (node->levels_remaining.fetch_sub(1, std::memory_order_acq_rel) == 1) {
      enqueue_pending_upper_delete(node);
    }
  }

  // Cascading top-down search across all upper levels (2.4節): starts at the highest
  // level's head and, at each level, walks right as far as possible before dropping down
  // one level from the same horizontal position — the standard skip-list search, built on
  // marked_list_find (marked_list.hpp) once per level. Returns the durable_offset of the
  // level-1 predecessor as a Level 0 search hint.
  //
  // `pred` carried over from the level above is exactly the same kind of thing as Level 0's
  // find_at_or_after `hint`: usually a shortcut, but possibly marked by the time this level
  // reads it. Its fallback can't be itself (unlike find_upper_at_level below, which always
  // starts at a head and never needs one) — it must be this level's own head, mirroring
  // find_at_or_after's hint-falls-back-to-kHead.
  [[nodiscard]] auto search_upper_levels(const Key &key) const -> UpperSearchResult {
    UpperSearchResult result;
    UpperNode *pred = nullptr;
    for (int level = kDefaultMaxLevel; level >= 1; --level) {
      UpperNode *found_pred = nullptr;
      static_cast<void>(find_upper_at_level_from(pred, key, level, &found_pred));
      pred = found_pred;
    }
    if (pred != nullptr) {
      result.level0_hint = pred->durable_offset;
    }
    return result;
  }

  // The one-level search both search_upper_levels (cascading, `start` carried down from the
  // level above) and link_upper_levels (single-level, `start` always null — a fresh
  // positioning search per level) need: stops at the first node whose key is >= `key`, which
  // is exactly where a new node with this key belongs. Wraps marked_list_find so both
  // callers share the same next/key/is_dead/on_splice policies instead of repeating them.
  [[nodiscard]] auto find_upper_at_level_from(UpperNode *start,
                                              const Key &key,
                                              int level,
                                              UpperNode **out_pred) const -> UpperNode * {
    return marked_list_find<UpperNode *, PointerMarkedTraits<UpperNode>>(
        start,
        upper_word(start, level),
        nullptr,
        upper_heads_[level - 1],
        key,
        less_,
        [level](UpperNode *n) -> std::atomic<uint64_t> & { return n->forwards[level - 1]; },
        [this](UpperNode *n) -> const Key & { return nodes_[n->durable_offset].key; },
        [this](UpperNode *n) { return is_upper_node_dead(n); },
        [this](UpperNode *n) { on_upper_splice(n); },
        out_pred);
  }

  [[nodiscard]] auto find_upper_at_level(const Key &key, int level, UpperNode **out_pred) const -> UpperNode * {
    return find_upper_at_level_from(nullptr, key, level, out_pred);
  }

  // Single-level search for one specific durable_offset, not just any node with a matching
  // key — remove()'s upper-level cleanup can't rely on key alone: an entirely different
  // occurrence of the same key can already have been removed and reinserted, landing a
  // different UpperNode at this same sorted position, so this scans past same-key entries
  // until the offset matches (or the key strictly exceeds `key`). Marking doesn't touch a
  // node's successor value (marked_list_mark_for_deletion), so it's safe to keep walking
  // through a marked node here without helping it off — some other search will.
  [[nodiscard]] auto find_upper_node_at_level(Offset target_offset,
                                              const Key &key,
                                              int level,
                                              UpperNode **out_pred) const -> UpperNode * {
    UpperNode *pred = nullptr;
    UpperNode *current = marked_ptr_value<UpperNode>(upper_heads_[level - 1].load(std::memory_order_acquire));
    while (current != nullptr && !less_(key, nodes_[current->durable_offset].key)) {
      if (current->durable_offset == target_offset) {
        *out_pred = pred;
        return current;
      }
      pred = current;
      current = marked_ptr_value<UpperNode>(current->forwards[level - 1].load(std::memory_order_acquire));
    }
    *out_pred = pred;
    return nullptr;
  }

  // Bottom-up insert into levels 1..height (8章, ASCS insert order), lock-free: each level's
  // CAS validates "the successor is still what I read" and "the predecessor isn't itself
  // being marked out from under me" in one shot (marked_list.hpp), so a losing race just
  // means retrying that level's positioning search, never data loss or corruption.
  //
  // put()'s Level 0 CAS makes `fresh` live and reachable before this runs, so a concurrent
  // remove() on the same key can tombstone it before any of this has happened. Checking once
  // up front skips the insert entirely in the common case — Level 0's O(N) fallback still
  // finds the key correctly without an upper-level entry. It isn't airtight on its own
  // (remove() could still win on the very last level, after this check passed): the backstop
  // is is_upper_node_dead() above, which every future search checks for every node it visits
  // regardless of who created it or when — so a rare entry that slips past this check is
  // still guaranteed to be found, marked, and reclaimed by the next search that reaches it.
  void link_upper_levels(Offset fresh, const Key &key, int height) {
    const PackedValue v(nodes_[fresh].value.load(std::memory_order_acquire));
    if (v.state() != NodeState::kLive) {
      return;
    }
    UpperNode *node = allocate_upper_node(fresh, height);
    for (int level = 1; level <= height; ++level) {
      for (;;) {
        UpperNode *pred = nullptr;
        UpperNode *successor = find_upper_at_level(key, level, &pred);
        node->forwards[level - 1].store(pack_marked_ptr(successor, false), std::memory_order_relaxed);
        uint64_t expected = pack_marked_ptr(successor, false);
        const uint64_t desired = pack_marked_ptr(node, false);
        if (upper_word(pred, level).compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
          break;
        }
        // Predecessor changed (a racing insert/delete nearby, or it was itself just marked)
        // — reposition at this level and retry.
      }
    }
  }

  // Top-down eager cleanup of one specific node's upper-level entries (8章, ASCS delete
  // order) — an optimization, not a correctness requirement: is_upper_node_dead() (above)
  // guarantees any level this misses still gets marked, spliced, and reclaimed the next time
  // any search passes through it, exactly as if this had never been called. `target_offset`
  // identifies exactly which occurrence of `key` to remove — see find_upper_node_at_level().
  void unlink_upper_levels(const Key &key, Offset target_offset) {
    for (int level = kDefaultMaxLevel; level >= 1; --level) {
      UpperNode *pred = nullptr;
      UpperNode *current = find_upper_node_at_level(target_offset, key, level, &pred);
      if (current == nullptr) {
        continue;  // this occurrence never reached this level
      }
      marked_list_mark_for_deletion<UpperNode *, PointerMarkedTraits<UpperNode>>(
          current, [level](UpperNode *n) -> std::atomic<uint64_t> & { return n->forwards[level - 1]; });
      const uint64_t successor_raw = current->forwards[level - 1].load(std::memory_order_acquire);
      uint64_t expected = pack_marked_ptr(current, false);
      const uint64_t desired = pack_marked_ptr(marked_ptr_value<UpperNode>(successor_raw), false);
      if (upper_word(pred, level).compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
        on_upper_splice(current);
      }
      // A failed splice here just means a concurrent change beat us to it (possibly already
      // helped by another search) — nothing to redo, the node is still marked either way.
    }
  }

  // Lock-free stack of UpperNodes awaiting deallocation, linked via their own dedicated
  // next_pending field (upper_node.hpp) — never forwards[], which a concurrent reader may
  // still legitimately dereference after this node is unlinked (see there for why).
  void enqueue_pending_upper_delete(UpperNode *node) const {
    stack_push(pending_upper_deletes_, node, [](UpperNode *n, UpperNode *next) {
      n->next_pending.store(next, std::memory_order_relaxed);
    });
  }

  std::filesystem::path path_;
  MmapFile file_;
  DurableNode<Key> *nodes_;
  size_t capacity_slots_;
  std::atomic<Offset> high_water_mark_{2};
  Compare less_{};
  LevelGenerator level_generator_;
  // Both mutable: search functions are logically const (they only ever refine a hint) but
  // physically mutate these via marked_list_find's helping splices and on_upper_splice's
  // reclaim-queue push, exactly as Level 0's `nodes_` (a pointer, not const-propagated
  // through `this`) already allows for forward0.
  mutable std::array<std::atomic<uint64_t>, kDefaultMaxLevel> upper_heads_{};
  mutable std::atomic<UpperNode *> pending_upper_deletes_{nullptr};

  mutable std::array<EpochSlot, 2> epoch_slots_{};
  mutable std::atomic<uint64_t> epoch_{0};
  std::mutex epoch_mutex_;
  mutable std::atomic<Offset> pending_head_{kNullOffset};
  std::atomic<uint64_t> free_head_{0};

  // Epoch of the last successful checkpoint() — distinct from epoch_, which is also bumped
  // by reclaim() for EBR purposes and so isn't 1:1 with "how many checkpoints have
  // happened." See shadow_if_first_touch_since_checkpoint().
  mutable std::atomic<uint64_t> last_published_epoch_{0};
  // Offsets tombstoned by remove(), awaiting checkpoint()-gated physical unlink — see
  // enqueue_pending_checkpoint_unlink().
  mutable std::atomic<Offset> pending_checkpoint_unlink_{kNullOffset};
};

}  // namespace pskiplist

#define PSKIPLIST_VERSION_MAJOR 0
#define PSKIPLIST_VERSION_MINOR 1
#define PSKIPLIST_VERSION_PATCH 0
#define PSKIPLIST_VERSION (PSKIPLIST_VERSION_MAJOR * 10000 + PSKIPLIST_VERSION_MINOR * 100 + PSKIPLIST_VERSION_PATCH)

