// Generated by scripts/amalgamate.sh from include/pskiplist/detail/*.hpp. Do not edit
// directly — edit the sources under detail/ and regenerate.
#pragma once

#include <concepts>
#include <type_traits>

namespace pskiplist {

// Key is stored as raw bytes directly in the mmap'd file (2.1節) and is never
// placement-new constructed slot-by-slot — only trivially copyable types can be safely
// read from and overwritten onto memory that was never explicitly constructed.
template <typename Key>
concept SkipListKey = std::is_trivially_copyable_v<Key> && std::default_initializable<Key>;

// Same requirements as SkipListKey — `Value` is stored and copied the same way, just without
// needing an ordering.
template <typename Value>
concept SkipListValue = std::is_trivially_copyable_v<Value> && std::default_initializable<Value>;

template <typename Compare, typename Key>
concept SkipListCompare = std::default_initializable<Compare> && std::predicate<Compare, const Key &, const Key &>;

}  // namespace pskiplist

#include <atomic>
#include <cstdint>

#include <cstdint>

namespace pskiplist {

using Offset = uint64_t;
inline constexpr uint64_t kForwardMarkBit = uint64_t{1} << 63;
inline constexpr Offset kNullOffset = kForwardMarkBit - 1;

[[nodiscard]] inline constexpr auto pack_forward(Offset offset, bool marked) -> uint64_t {
  return offset | (marked ? kForwardMarkBit : uint64_t{0});
}
[[nodiscard]] inline constexpr auto forward_offset(uint64_t raw) -> Offset { return raw & ~kForwardMarkBit; }
[[nodiscard]] inline constexpr auto forward_marked(uint64_t raw) -> bool { return (raw & kForwardMarkBit) != 0; }

// A tagged (offset, generation counter) word for the free list's Treiber stack head: the
// counter changes on every push/pop, ruling out ABA for a thread that stalls mid-pop and
// later CASes against a stale head that coincidentally names the same offset again.
inline constexpr int kTaggedOffsetBits = 40;
inline constexpr uint64_t kTaggedOffsetMask = (uint64_t{1} << kTaggedOffsetBits) - 1;
inline constexpr Offset kMaxTaggedOffset = kTaggedOffsetMask;

inline constexpr uint32_t kTaggedGenerationMask = (uint32_t{1} << (64 - kTaggedOffsetBits)) - 1;

[[nodiscard]] inline constexpr auto pack_tagged(Offset offset, uint32_t tag) -> uint64_t {
  return (offset & kTaggedOffsetMask) | (static_cast<uint64_t>(tag & kTaggedGenerationMask) << kTaggedOffsetBits);
}
[[nodiscard]] inline constexpr auto tagged_offset(uint64_t raw) -> Offset { return raw & kTaggedOffsetMask; }
[[nodiscard]] inline constexpr auto tagged_generation(uint64_t raw) -> uint32_t {
  return static_cast<uint32_t>(raw >> kTaggedOffsetBits);
}

}  // namespace pskiplist

#include <cstdint>

namespace pskiplist {

// A node's lifecycle: kLive (findable, its value trustworthy), kTombstonedLinked (logically
// removed, but still linked into Level 0 — physical unlink is deferred to checkpoint()),
// kTombstonedUnlinked (physical unlink completed; the offset is retired for good and will be
// reclaimed). Kept as its own field (durable_node.hpp) rather than packed into `value`'s bits,
// so `Value` can be an arbitrary trivially-copyable type with no bits reserved for state.
enum class NodeState : uint8_t {
  kLive = 0,
  kTombstonedLinked = 1,
  kTombstonedUnlinked = 2,
};

}  // namespace pskiplist

namespace pskiplist {

template <typename Key, typename Value = uint64_t>
struct DurableNode {
  std::atomic<uint64_t> epoch{0};  // creation epoch, set once at allocation
  Key key{};
  std::atomic<NodeState> state{NodeState::kLive};
  // Shadow of `state`/`value` as of the last checkpoint, and the epoch of the most recent
  // mutation — see skiplist.hpp's write_value_locked() / recover(). checkpointed_state exists
  // because reverting `value` alone during recover() no longer implies reverting state too, now
  // that they're separate fields instead of one packed word.
  std::atomic<NodeState> checkpointed_state{NodeState::kLive};
  // Seqlock guarding `value`: even = stable, odd = a write is in flight. Also doubles as the
  // write-side mutual exclusion (CAS even->odd) for concurrent put()s targeting this node — see
  // skiplist.hpp's write_value_locked()/read_value().
  mutable std::atomic<uint64_t> version{0};
  Value value{};
  Value checkpointed_value{};
  std::atomic<uint64_t> mutation_epoch{0};
  mutable std::atomic<uint64_t> forward0{pack_forward(kNullOffset, false)};
  // Checkpoint-gated physical-unlink queue linkage — see enqueue_pending_checkpoint_unlink().
  std::atomic<Offset> next_checkpoint_unlink{kNullOffset};
  std::atomic<bool> pending_checkpoint_unlink_queued{false};
};

}  // namespace pskiplist

#include <array>
#include <atomic>
#include <cstdint>

namespace pskiplist {

enum class EpochRole : uint8_t {
  kReader,
  kWriter,
};

// Per-parity-slot active counts, split by role: reclaim() waits for both readers and writers
// to drain (either could hold a stale offset), checkpoint() waits only for writers (a reader
// never mutates anything msync() could tear).
struct EpochSlot {
  std::atomic<int64_t> readers{0};
  std::atomic<int64_t> writers{0};
};

// RAII registration into whichever of `slots[0]`/`slots[1]` matches `epoch`'s current parity,
// under the counter matching `role`. Whoever advances `epoch` and waits for the slot it
// vacated to drain treats anything observed under it as safe to act on.
class EpochToken {
 public:
  // Load-then-increment isn't atomic: a thread can read `epoch`, stall, and have reclaim()
  // drain that exact slot to 0 and free memory before the fetch_add lands. Re-reading `epoch`
  // after incrementing catches this — if it moved, undo and retry under the now-current
  // parity, which reclaim() can't have started draining yet.
  EpochToken(std::array<EpochSlot, 2> &slots, std::atomic<uint64_t> &epoch, EpochRole role)
      : slots_(slots), role_(role) {
    for (;;) {
      parity_ = epoch.load(std::memory_order_acquire) & 1;
      counter().fetch_add(1, std::memory_order_acq_rel);
      if ((epoch.load(std::memory_order_acquire) & 1) == parity_) {
        break;
      }
      counter().fetch_sub(1, std::memory_order_acq_rel);
    }
  }
  ~EpochToken() { counter().fetch_sub(1, std::memory_order_acq_rel); }
  EpochToken(const EpochToken &) = delete;
  auto operator=(const EpochToken &) -> EpochToken & = delete;

 private:
  [[nodiscard]] auto counter() -> std::atomic<int64_t> & {
    return role_ == EpochRole::kReader ? slots_[parity_].readers : slots_[parity_].writers;
  }

  std::array<EpochSlot, 2> &slots_;
  EpochRole role_;
  uint64_t parity_;
};

}  // namespace pskiplist

#include <cstdint>
#include <functional>
#include <random>
#include <thread>

namespace pskiplist {

inline constexpr double kDefaultLevelPromotionProbability = 0.25;
inline constexpr int kDefaultMaxLevel = 32;

// Assigns each new node's participation height via a geometric distribution (2.5節):
// starting at level 1, promotes to the next level with probability `p` until it stops or
// reaches `max_level`. RNG state is thread-local, seeded once per thread from `seed`
// combined with the calling thread's id — concurrent callers never synchronize on a
// shared generator, and a fixed `seed` gives a reproducible sequence for single-threaded
// use (6章's fault-injection tests), without claiming exact reproducibility across
// concurrent interleavings.
class LevelGenerator {
 public:
  explicit LevelGenerator(uint64_t seed, int max_level = kDefaultMaxLevel, double p = kDefaultLevelPromotionProbability)
      : seed_(seed), max_level_(max_level), p_(p) {}

  [[nodiscard]] auto next_level() const -> int {
    thread_local std::mt19937_64 rng(seed_ ^ std::hash<std::thread::id>{}(std::this_thread::get_id()));
    std::uniform_real_distribution<double> unit(0.0, 1.0);
    int level = 1;
    while (level < max_level_ && unit(rng) < p_) {
      ++level;
    }
    return level;
  }

 private:
  uint64_t seed_;
  int max_level_;
  double p_;
};

}  // namespace pskiplist

#include <fcntl.h>
#include <unistd.h>

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <optional>
#include <system_error>

namespace pskiplist {

inline constexpr uint32_t kManifestMagic = 0x504b4c31;  // "PKL1"
inline constexpr uint8_t kManifestFormatVersion = 1;

// 32B fixed manifest header (3章). A mismatched format_version is treated identically to
// a missing manifest — no migration is implemented.
struct ManifestHeader {
  uint32_t magic = kManifestMagic;
  uint8_t format_version = kManifestFormatVersion;
  uint8_t reserved[3] = {};
  uint64_t epoch = 0;            // node epoch stamps <= this are trusted as durable
  uint64_t high_water_mark = 0;  // bump allocation's last reached offset
  uint64_t checksum = 0;         // FNV-1a64 of this header with checksum itself zeroed
};
static_assert(sizeof(ManifestHeader) == 32);

[[nodiscard]] inline auto manifest_checksum(const ManifestHeader &header) -> uint64_t {
  ManifestHeader zeroed = header;
  zeroed.checksum = 0;
  const auto *bytes = reinterpret_cast<const unsigned char *>(&zeroed);
  uint64_t hash = 0xcbf29ce484222325ULL;
  for (size_t i = 0; i < sizeof(zeroed); ++i) {
    hash ^= bytes[i];
    hash *= 0x100000001b3ULL;
  }
  return hash;
}

[[nodiscard]] inline auto manifest_path(const std::filesystem::path &data_path) -> std::filesystem::path {
  auto path = data_path;
  path += ".manifest";
  return path;
}

// Writes the manifest for `data_path` via temp file + fsync + atomic rename (3章), so a
// reader never observes a partially-written manifest.
inline void write_manifest(const std::filesystem::path &data_path, uint64_t epoch, uint64_t high_water_mark) {
  ManifestHeader header;
  header.epoch = epoch;
  header.high_water_mark = high_water_mark;
  header.checksum = manifest_checksum(header);

  const auto final_path = manifest_path(data_path);
  auto tmp_path = final_path;
  tmp_path += ".tmp";

  const int fd = ::open(tmp_path.c_str(), O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if (fd < 0) {
    throw std::system_error(errno, std::generic_category(), "open(" + tmp_path.string() + ")");
  }
  const ssize_t written = ::write(fd, &header, sizeof(header));
  if (written != static_cast<ssize_t>(sizeof(header))) {
    const int err = errno;
    ::close(fd);
    throw std::system_error(err, std::generic_category(), "write(" + tmp_path.string() + ")");
  }
  if (::fsync(fd) != 0) {
    const int err = errno;
    ::close(fd);
    throw std::system_error(err, std::generic_category(), "fsync(" + tmp_path.string() + ")");
  }
  ::close(fd);

  std::error_code ec;
  std::filesystem::rename(tmp_path, final_path, ec);
  if (ec) {
    throw std::system_error(ec, "rename(" + tmp_path.string() + " -> " + final_path.string() + ")");
  }
}

// Returns nullopt if the manifest is missing, truncated, has a mismatched magic or
// format_version, or fails its checksum — any of these are treated as "no checkpoint has
// ever completed for this file".
[[nodiscard]] inline auto read_manifest(const std::filesystem::path &data_path) -> std::optional<ManifestHeader> {
  const auto path = manifest_path(data_path);
  const int fd = ::open(path.c_str(), O_RDONLY);
  if (fd < 0) return std::nullopt;

  ManifestHeader header{};
  const ssize_t bytes_read = ::read(fd, &header, sizeof(header));
  ::close(fd);
  if (bytes_read != static_cast<ssize_t>(sizeof(header))) return std::nullopt;
  if (header.magic != kManifestMagic) return std::nullopt;
  if (header.format_version != kManifestFormatVersion) return std::nullopt;
  if (manifest_checksum(header) != header.checksum) return std::nullopt;

  return header;
}

}  // namespace pskiplist

#include <atomic>
#include <cstdint>

namespace pskiplist {

// Generic lock-free "find, helping to unlink any marked node along the way" search over a
// singly-linked list, shared by Level 0 (Identity = Offset) and the upper levels (Identity =
// UpperNode*). Each node's "next" pointer is packed with a deletion mark bit into one
// atomic<uint64_t> word (Traits::pack/value/is_marked), so a single CAS on a predecessor's
// word validates both "the successor is still what I read" and "the predecessor itself
// hasn't been marked out from under me".
//
// `start_id`/`start_word` is where the walk begins (a search hint); if it's already marked,
// the walk restarts from the guaranteed-live `fallback_id`/`fallback_word` (a list head)
// instead. Marking a node for deletion is entirely the caller's job (remove()'s
// unlink_upper_levels()/physically_unlink_best_effort() do this directly, with a
// retry-until-success loop — see marked_list_mark_for_deletion below) — this function only
// ever *discovers* an already-marked node (via `Traits::is_marked`, read straight off the
// node's own next-word, no other node touched) and helps splice it out, reporting the splice
// via `on_splice` on a winning CAS, then restarts from the start. Returns the first node with
// key >= `key`, or Traits::null_id() if the list runs out; `*out_pred` receives its
// predecessor.
template <typename Identity,
          typename Traits,
          typename Key,
          typename Less,
          typename NextWordFn,
          typename KeyFn,
          typename OnSpliceFn>
[[nodiscard]] auto marked_list_find(Identity start_id,
                                    std::atomic<uint64_t> &start_word,
                                    Identity fallback_id,
                                    std::atomic<uint64_t> &fallback_word,
                                    const Key &key,
                                    Less less,
                                    NextWordFn next_word,
                                    KeyFn key_of,
                                    OnSpliceFn on_splice,
                                    Identity *out_pred) -> Identity {
  Identity anchor_id = start_id;
  std::atomic<uint64_t> *anchor_word = &start_word;
  for (;;) {
    Identity pred = anchor_id;
    std::atomic<uint64_t> *pred_word = anchor_word;
    const uint64_t pred_raw = pred_word->load(std::memory_order_acquire);
    if (Traits::is_marked(pred_raw)) {
      anchor_id = fallback_id;
      anchor_word = &fallback_word;
      continue;
    }
    Identity current = Traits::value(pred_raw);
    for (;;) {
      if (current == Traits::null_id()) {
        *out_pred = pred;
        return current;
      }
      const uint64_t current_raw = next_word(current).load(std::memory_order_acquire);
      if (Traits::is_marked(current_raw)) {
        const Identity successor = Traits::value(current_raw);
        uint64_t expected = Traits::pack(current, false);
        const uint64_t desired = Traits::pack(successor, false);
        if (pred_word->compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
          on_splice(current);
        }
        break;  // restart the whole walk from anchor_id/anchor_word — pred_word may now be stale
      }
      if (!less(key_of(current), key)) {
        *out_pred = pred;
        return current;
      }
      pred = current;
      pred_word = &next_word(current);
      current = Traits::value(current_raw);
    }
  }
}

// Marks `id`'s own word for logical deletion, preserving its current successor — the first
// half of removing a node, before any splice is attempted. No-op if already marked.
template <typename Identity, typename Traits, typename OwnWordFn>
void marked_list_mark_for_deletion(Identity id, OwnWordFn own_word) {
  uint64_t raw = own_word(id).load(std::memory_order_acquire);
  while (!Traits::is_marked(raw)) {
    const uint64_t desired = Traits::pack(Traits::value(raw), true);
    if (own_word(id).compare_exchange_strong(raw, desired, std::memory_order_acq_rel)) {
      break;
    }
  }
}

// Lock-free Treiber stack push: `value` becomes the new head, linked via `set_next(value,
// old_head)` (a callback rather than a plain word store, so a caller can repurpose an
// existing word — e.g. packing in a mark bit). No pop: every user drains the whole stack at
// once via `head.exchange(...)`, so there's no ABA hazard here (unlike the free list, which
// needs marked_offset.hpp's tagged pointer).
template <typename Identity, typename SetNextFn>
void stack_push(std::atomic<Identity> &head, Identity value, SetNextFn set_next) {
  Identity old_head = head.load(std::memory_order_relaxed);
  do {
    set_next(value, old_head);
  } while (!head.compare_exchange_weak(old_head, value, std::memory_order_acq_rel, std::memory_order_relaxed));
}

}  // namespace pskiplist

#include <cstdint>

namespace pskiplist {

// Marks a pointer's low bit to signal logical deletion (marked_offset.hpp's kForwardMarkBit
// idea, applied to bit 0 instead of bit 63) — safe since `::operator new` addresses are
// always aligned well beyond 2 bytes.
template <typename T>
[[nodiscard]] inline auto pack_marked_ptr(T *ptr, bool marked) -> uintptr_t {
  const auto value = reinterpret_cast<uintptr_t>(ptr);
  return marked ? (value | uintptr_t{1}) : value;
}

template <typename T>
[[nodiscard]] inline auto marked_ptr_value(uintptr_t raw) -> T * {
  return reinterpret_cast<T *>(raw & ~uintptr_t{1});
}

[[nodiscard]] inline auto marked_ptr_marked(uintptr_t raw) -> bool { return (raw & uintptr_t{1}) != 0; }

// marked_list.hpp traits binding it to pointer identities (null_id() is nullptr, unlike
// Level 0's offset-based kTail sentinel).
template <typename T>
struct PointerMarkedTraits {
  static auto pack(T *id, bool marked) -> uint64_t { return pack_marked_ptr<T>(id, marked); }
  static auto value(uint64_t raw) -> T * { return marked_ptr_value<T>(raw); }
  static auto is_marked(uint64_t raw) -> bool { return marked_ptr_marked(raw); }
  static auto null_id() -> T * { return nullptr; }
};

}  // namespace pskiplist

#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <cstddef>
#include <filesystem>
#include <stdexcept>
#include <system_error>

namespace pskiplist {

// RAII POSIX file opened, sized, and mapped MAP_SHARED for direct in-place mutation. Sized
// once at construction and never grown. A brand-new file is zero-extended to size_bytes; an
// existing one must already be exactly that size.
class MmapFile {
 public:
  MmapFile(const std::filesystem::path &path, size_t size_bytes) : size_(size_bytes) {
    fd_ = ::open(path.c_str(), O_RDWR | O_CREAT, 0644);
    if (fd_ < 0) {
      throw std::system_error(errno, std::generic_category(), "open(" + path.string() + ")");
    }

    struct stat st {};
    if (::fstat(fd_, &st) != 0) {
      const int err = errno;
      ::close(fd_);
      throw std::system_error(err, std::generic_category(), "fstat(" + path.string() + ")");
    }

    if (st.st_size == 0) {
      if (::ftruncate(fd_, static_cast<off_t>(size_)) != 0) {
        const int err = errno;
        ::close(fd_);
        throw std::system_error(err, std::generic_category(), "ftruncate(" + path.string() + ")");
      }
    } else {
      reused_ = true;
      if (static_cast<size_t>(st.st_size) != size_) {
        ::close(fd_);
        throw std::invalid_argument("pskiplist: " + path.string() +
                                    " exists with a size that does not match capacity_bytes");
      }
    }

    data_ = ::mmap(nullptr, size_, PROT_READ | PROT_WRITE, MAP_SHARED, fd_, 0);
    if (data_ == MAP_FAILED) {
      const int err = errno;
      ::close(fd_);
      throw std::system_error(err, std::generic_category(), "mmap(" + path.string() + ")");
    }
  }

  ~MmapFile() {
    if (data_ != nullptr && data_ != MAP_FAILED) {
      ::munmap(data_, size_);
    }
    if (fd_ >= 0) {
      ::close(fd_);
    }
  }

  MmapFile(const MmapFile &) = delete;
  auto operator=(const MmapFile &) -> MmapFile & = delete;

  [[nodiscard]] auto data() const -> void * { return data_; }
  [[nodiscard]] auto size() const -> size_t { return size_; }
  // True if `path` already existed with content (i.e. wasn't freshly created) —
  // PSkipList uses this to decide whether to run recovery instead of a fresh init.
  [[nodiscard]] auto reused() const -> bool { return reused_; }

  // Blocks until the mapping's dirty pages are durable on the underlying storage (3章).
  void sync() const {
    if (::msync(data_, size_, MS_SYNC) != 0) {
      throw std::system_error(errno, std::generic_category(), "msync");
    }
  }

 private:
  int fd_ = -1;
  void *data_ = nullptr;
  size_t size_ = 0;
  bool reused_ = false;
};

}  // namespace pskiplist

#include <algorithm>
#include <array>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <mutex>
#include <new>
#include <optional>
#include <random>
#include <stdexcept>
#include <thread>
#include <utility>
#include <vector>

#include <atomic>
#include <cstddef>
#include <cstdint>
#include <mutex>
#include <new>
#include <vector>

namespace pskiplist {

// Bump-pointer block arena backing UpperNode allocations (upper_node.hpp), mirroring RocksDB's
// memtable Arena (memory/arena.h). Upper levels are pure DRAM search hints, fully rebuilt from
// Level 0 on every recovery (PSkipList::rebuild_upper_levels()) -- unlike Level 0 they need no
// persistence or crash-safety story, only fast, densely-packed allocation. Individual nodes are
// never freed one at a time: instead each block tracks how many of its nodes are still live
// (`live_count`), and the block's underlying buffer is only actually freed once that count
// reaches zero *and* the block has been retired (superseded as the bump-allocation target) --
// see release()/maybe_queue_for_free(). Because rebuild_upper_levels() walks Level 0 in sorted
// key order, nodes allocated during a rebuild land in the arena in that same order, giving
// nearby keys' UpperNodes real physical locality that a plain per-node `::operator new` has no
// way to offer.
class UpperArena {
 public:
  struct Block {
    std::byte *data = nullptr;
    size_t capacity = 0;
    std::atomic<size_t> bump_offset{0};
    std::atomic<int> live_count{0};
    std::atomic<bool> retired{false};
    // Guards against release() and install_new_block() both observing "retired && live_count ==
    // 0" for the same block and queueing it for a free twice.
    std::atomic<bool> queued_for_free{false};
  };

  static constexpr size_t kDefaultBlockSize = 1 << 20;  // 1MB

  explicit UpperArena(size_t block_size = kDefaultBlockSize) : block_size_(block_size) {
    current_.store(new_block(block_size_), std::memory_order_relaxed);
  }

  ~UpperArena() {
    // The whole PSkipList (and this arena along with it) is being destroyed -- no concurrent
    // access is possible any more, so every block ever created is freed unconditionally here,
    // regardless of whether drain_pending_blocks() already got to it (a block whose buffer was
    // already freed has `data == nullptr`; deleting a null array is a no-op).
    for (Block *block : all_blocks_) {
      delete[] block->data;
      delete block;
    }
  }

  UpperArena(const UpperArena &) = delete;
  auto operator=(const UpperArena &) -> UpperArena & = delete;

  // Bump-allocates `bytes` from the current block (rounded up to kAlignUnit so every allocation
  // is at least std::max_align_t-aligned, sufficient for the std::atomic<uint64_t> forward-
  // pointer array placed inside it). Installs a fresh block if the current one doesn't fit it,
  // or -- if `bytes` alone exceeds a normal block -- an "irregular" block sized exactly to it,
  // mirroring RocksDB's Arena. Thread-safe: lock-free on the common path; only the (rare) thread
  // that actually loses the race to fill a block pays the blocks_mutex_ cost of installing the
  // next one. Returns the raw memory and, via `out_block`, the block it came from -- callers
  // must pass that same block to release() exactly once when the allocation is retired.
  [[nodiscard]] auto allocate(size_t bytes, Block **out_block) -> std::byte * {
    bytes = align_up(bytes);
    for (;;) {
      Block *block = current_.load(std::memory_order_acquire);
      size_t offset = block->bump_offset.load(std::memory_order_relaxed);
      for (;;) {
        if (offset + bytes > block->capacity) {
          break;
        }
        if (block->bump_offset.compare_exchange_weak(
                offset, offset + bytes, std::memory_order_acq_rel, std::memory_order_relaxed)) {
          block->live_count.fetch_add(1, std::memory_order_relaxed);
          *out_block = block;
          return block->data + offset;
        }
      }
      install_new_block(block, bytes);
    }
  }

  // Decrements `block`'s live count. If this was the last live node in a block that has already
  // been retired, queues the block's buffer for freeing -- NOT freed immediately: a writer that
  // read `current_` just before retirement could still be mid-CAS against this block's (still
  // valid) memory, so actually freeing it here would race that straggler. The caller (PSkipList::
  // reclaim(), which already runs an epoch-based-reclamation drain proving no such straggler
  // remains active) must call drain_pending_blocks() after that drain to actually free anything
  // queued here.
  void release(Block *block) {
    if (block->live_count.fetch_sub(1, std::memory_order_acq_rel) == 1) {
      maybe_queue_for_free(block);
    }
  }

  // Actually frees every block queued by release()/install_new_block() so far. Safe to call only
  // after the caller has independently established (via EBR or an equivalent drain) that no
  // writer still holds a `current_`-derived reference to a retired block -- see release()'s
  // comment. Not called from allocate()/release() themselves, deliberately: freeing must be
  // externally paced by PSkipList::reclaim()'s own epoch drain, not by whichever thread happens
  // to observe a block's live_count hit zero.
  void drain_pending_blocks() {
    std::vector<Block *> to_free;
    {
      std::lock_guard<std::mutex> lock(pending_free_mutex_);
      to_free.swap(pending_free_);
    }
    for (Block *block : to_free) {
      delete[] block->data;
      block->data = nullptr;
    }
  }

 private:
  static constexpr size_t kAlignUnit = alignof(std::max_align_t);
  static auto align_up(size_t n) -> size_t { return (n + kAlignUnit - 1) & ~(kAlignUnit - 1); }

  // Not locked itself -- called either before any concurrency exists (constructor) or by a
  // caller already holding blocks_mutex_ (install_new_block()).
  auto new_block(size_t size) -> Block * {
    auto *block = new Block();
    block->data = new std::byte[size];
    block->capacity = size;
    all_blocks_.push_back(block);
    return block;
  }

  // Installs a fresh block as the new bump-allocation target and retires `old_current`. Only the
  // thread that wins blocks_mutex_ actually installs one; every other thread racing to fill the
  // same block just finds current_ already updated on its next outer-loop iteration and retries
  // against the fresh block.
  void install_new_block(Block *old_current, size_t min_bytes) {
    const std::lock_guard<std::mutex> lock(blocks_mutex_);
    if (current_.load(std::memory_order_acquire) != old_current) {
      return;  // another thread already installed one while we were waiting for the lock
    }
    const size_t new_size = min_bytes > block_size_ ? min_bytes : block_size_;
    Block *fresh = new_block(new_size);
    current_.store(fresh, std::memory_order_release);
    old_current->retired.store(true, std::memory_order_release);
    maybe_queue_for_free(old_current);
  }

  void maybe_queue_for_free(Block *block) {
    if (!block->retired.load(std::memory_order_acquire)) {
      return;  // still the current bump target -- more nodes may yet be allocated from it
    }
    if (block->live_count.load(std::memory_order_acquire) != 0) {
      return;  // still has live nodes
    }
    bool expected = false;
    if (!block->queued_for_free.compare_exchange_strong(expected, true, std::memory_order_acq_rel)) {
      return;  // release() and install_new_block() both observed zero -- only one queues it
    }
    const std::lock_guard<std::mutex> lock(pending_free_mutex_);
    pending_free_.push_back(block);
  }

  size_t block_size_;
  std::atomic<Block *> current_;

  std::mutex blocks_mutex_;
  std::vector<Block *> all_blocks_;  // every block ever created, for the destructor's final sweep

  std::mutex pending_free_mutex_;
  std::vector<Block *> pending_free_;  // retired, zero-live blocks awaiting drain_pending_blocks()
};

}  // namespace pskiplist

#include <atomic>
#include <cstddef>
#include <cstdint>
#include <new>

namespace pskiplist {

// A volatile, DRAM-only skip-list node holding up to kCapacity (key, durable_offset) entries
// clustered around the same region of key space, instead of the classic "one node per key"
// skip-list design: a plain one-key-per-node skip list pays one random, likely cache-cold
// memory access per hop, which dominates Get/Scan cost at scale (measured: ~40+ such accesses
// per Get at 5M keys, even after moving the node's own memory into an arena -- see
// upper_arena.hpp -- since arena-allocation order only correlates with key order for a sorted
// bulk load, not for steady-state random-order inserts). Packing several nearby keys into one
// arena-resident, contiguous chunk turns most of those hops into a single cache-friendly linear
// scan over already-fetched memory instead.
//
// No splits or merges: `primary_key`/`primary_offset` fix a chunk's position in the outer
// linked list for its entire lifetime (see skiplist.hpp's cascade_upper_levels(), which compares
// chunks by `primary_key` exactly as it used to compare single-key nodes). Every key whose
// value falls in this chunk's "territory" -- between its primary_key and the next chunk's --
// is packed into one of its remaining entry slots via a lock-free claim (try_insert_into_chunk()
// in skiplist.hpp), no linked-list mutation needed. Once a chunk's capacity is exhausted, the
// next key in its territory instead gets its own brand new chunk, spliced in via the same
// CAS-based per-level insertion a fresh chunk always uses -- which incidentally subdivides the
// full chunk's territory going forward. Older entries already packed into the full chunk are
// never rebalanced or moved. This means chunk occupancy is uneven over time under heavy
// churn -- an accepted tradeoff for never needing an in-place split/merge algorithm.
template <typename Key>
struct UpperChunk {
  static constexpr int kCapacity = 32;

  struct Entry {
    Key key{};
    Offset durable_offset{kNullOffset};
    // published: separates a slot's claim (an atomic fetch_add on `claimed`) from making it
    // visible to readers -- a reader only trusts an entry once it observes published == true
    // (acquire); by that point the plain (non-atomic) key/durable_offset writes that happened
    // before the release store are guaranteed visible. `live` starts false and is set true only
    // once published; it flips back to false on removal but the slot itself is never reclaimed
    // individually -- see UpperChunk's own live_count for whole-chunk reclaim.
    std::atomic<bool> published{false};
    std::atomic<bool> live{false};
  };

  // Fixed at chunk creation, for this chunk's entire lifetime, independent of whether that
  // specific key is later removed -- this is purely a routing coordinate for the outer linked
  // list, not a claim that the primary entry is still live.
  Key primary_key{};
  Offset primary_offset{kNullOffset};

  std::atomic<int> claimed{0};     // next entry-slot index to hand out, capped at kCapacity
  std::atomic<int> live_count{0};  // entries not yet removed; the chunk unlinks once this hits 0
  int height = 0;
  std::atomic<int> levels_remaining{0};
  std::atomic<UpperChunk *> next_pending{nullptr};
  UpperArena::Block *owning_block = nullptr;
  Entry entries[kCapacity];
  std::atomic<uint64_t> forwards[1];  // actually `height` entries — see allocate_upper_chunk()
};

template <typename Key>
[[nodiscard]] inline auto allocate_upper_chunk(UpperArena &arena,
                                               Offset primary_offset,
                                               const Key &primary_key,
                                               int height) -> UpperChunk<Key> * {
  using Chunk = UpperChunk<Key>;
  const size_t bytes = sizeof(Chunk) + sizeof(std::atomic<uint64_t>) * static_cast<size_t>(height - 1);
  typename UpperArena::Block *block = nullptr;
  std::byte *memory = arena.allocate(bytes, &block);
  auto *chunk = reinterpret_cast<Chunk *>(memory);
  ::new (&chunk->primary_key) Key(primary_key);
  ::new (&chunk->primary_offset) Offset(primary_offset);
  ::new (&chunk->claimed) std::atomic<int>(1);  // slot 0 is the primary entry, claimed up front
  ::new (&chunk->live_count) std::atomic<int>(1);
  chunk->height = height;
  ::new (&chunk->levels_remaining) std::atomic<int>(height);
  ::new (&chunk->next_pending) std::atomic<Chunk *>(nullptr);
  chunk->owning_block = block;
  for (int i = 0; i < Chunk::kCapacity; ++i) {
    ::new (&chunk->entries[i]) typename Chunk::Entry();
  }
  chunk->entries[0].key = primary_key;
  chunk->entries[0].durable_offset = primary_offset;
  chunk->entries[0].live.store(true, std::memory_order_relaxed);
  chunk->entries[0].published.store(true, std::memory_order_release);
  for (int level = 0; level < height; ++level) {
    ::new (&chunk->forwards[level]) std::atomic<uint64_t>(pack_marked_ptr<Chunk>(nullptr, false));
  }
  return chunk;
}

// Arena-backed chunks are never individually destructed -- every field is a trivially
// destructible atomic or a trivially-copyable Key/Offset (see concepts.hpp's SkipListKey), so
// releasing the owning block's reference count (which may, once it hits zero on an
// already-retired block, queue that block's whole buffer for freeing -- see
// UpperArena::release()) is the entire cleanup this needs.
template <typename Key>
inline void deallocate_upper_chunk(UpperArena &arena, UpperChunk<Key> *chunk) {
  arena.release(chunk->owning_block);
}

}  // namespace pskiplist

namespace pskiplist {

template <typename Key, typename Value = uint64_t, typename Compare = std::less<Key>>
  requires SkipListKey<Key> && SkipListValue<Value> && SkipListCompare<Compare, Key>
class PSkipList {
 public:
  // `capacity_bytes` is fixed for the mapping's lifetime; size generously — a sparse file
  // only consumes disk for pages actually written.
  explicit PSkipList(const std::filesystem::path &path, size_t capacity_bytes)
      : path_(path),
        file_(path, capacity_bytes),
        nodes_(static_cast<DurableNode<Key, Value> *>(file_.data())),
        capacity_slots_(file_.size() / sizeof(DurableNode<Key, Value>)),
        level_generator_(std::random_device{}()) {
    if (capacity_slots_ < 2) {
      throw std::invalid_argument("pskiplist: capacity_bytes too small to hold head/tail sentinels");
    }
    if (capacity_slots_ > kMaxTaggedOffset) {
      throw std::invalid_argument("pskiplist: capacity_bytes exceeds the maximum representable node count");
    }
    if (file_.reused()) {
      recover();
    } else {
      initialize_fresh();
    }
  }

  ~PSkipList() {
    // Individual deallocate_upper_chunk() calls below just decrement each node's owning arena
    // block's live_count (see upper_arena.hpp) -- upper_arena_'s own destructor (a member,
    // destroyed after this body runs) unconditionally frees every block's buffer regardless of
    // live_count, so walking these lists here is about correctness of *use* (nothing else may
    // still be touching these nodes, since the whole PSkipList is being destroyed) rather than
    // about reclaiming memory that would otherwise leak.
    UpperChunk<Key> *current = marked_ptr_value<UpperChunk<Key>>(upper_heads_[0].load(std::memory_order_relaxed));
    while (current != nullptr) {
      UpperChunk<Key> *next = marked_ptr_value<UpperChunk<Key>>(current->forwards[0].load(std::memory_order_relaxed));
      deallocate_upper_chunk(upper_arena_, current);
      current = next;
    }
    UpperChunk<Key> *pending = pending_upper_deletes_.load(std::memory_order_relaxed);
    while (pending != nullptr) {
      UpperChunk<Key> *next = pending->next_pending.load(std::memory_order_relaxed);
      deallocate_upper_chunk(upper_arena_, pending);
      pending = next;
    }
  }

  PSkipList(const PSkipList &) = delete;
  auto operator=(const PSkipList &) -> PSkipList & = delete;

  [[nodiscard]] auto get(const Key &key) const -> std::optional<Value> {
    const auto found = get_with_key(key);
    if (!found.has_value()) return std::nullopt;
    return found->second;
  }

  // Like get(), but also returns the matched node's actual stored key — not merely `key` itself.
  // Useful when Compare/keys_equal treats keys as equal despite differing in some payload-carrying
  // bits Compare ignores (e.g. metadata packed into otherwise-unordered bits of a composite key).
  [[nodiscard]] auto get_with_key(const Key &key) const -> std::optional<std::pair<Key, Value>> {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kReader);
    Offset predecessor = kNullOffset;
    const Offset current = find_at_or_after(key, &predecessor, search_upper_levels(key).level0_hint);
    if (current == kNullOffset || current == kTail || !keys_equal(nodes_[current].key, key)) {
      return std::nullopt;
    }
    if (nodes_[current].state.load(std::memory_order_acquire) != NodeState::kLive) {
      return std::nullopt;
    }
    return std::make_pair(nodes_[current].key, read_value(current));
  }

  [[nodiscard]] auto put(const Key &key, const Value &payload) -> bool {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kWriter);
    const Offset hint = search_upper_levels(key).level0_hint;
    Offset fresh = kNullOffset;
    for (;;) {
      Offset predecessor = kNullOffset;
      const Offset existing = find_at_or_after(key, &predecessor, hint);
      if (existing != kNullOffset && existing != kTail && keys_equal(nodes_[existing].key, key)) {
        const NodeState state = nodes_[existing].state.load(std::memory_order_acquire);
        if (state == NodeState::kTombstonedUnlinked) {
          std::this_thread::yield();
          continue;
        }
        write_value_locked(existing, [&](Value &v) { v = payload; });
        if (state == NodeState::kTombstonedLinked) {
          NodeState expected = NodeState::kTombstonedLinked;
          if (!nodes_[existing].state.compare_exchange_strong(expected, NodeState::kLive, std::memory_order_acq_rel)) {
            // Lost the resurrect race to a concurrent physically_unlink_best_effort(), which
            // just committed to permanently retiring this offset -- the value write above is
            // harmless waste on a node that's about to be spliced out. Retry from the top.
            continue;
          }
        }
        return true;
      }

      if (fresh == kNullOffset) {
        fresh = allocate();
        if (fresh == kNullOffset) return false;
        nodes_[fresh].key = key;
        nodes_[fresh].value = payload;
        nodes_[fresh].epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_relaxed);
        // A reused slot may carry a previous occupant's state/shadow; reset it.
        nodes_[fresh].state.store(NodeState::kLive, std::memory_order_relaxed);
        nodes_[fresh].checkpointed_state.store(NodeState::kLive, std::memory_order_relaxed);
        nodes_[fresh].version.store(0, std::memory_order_relaxed);
        nodes_[fresh].checkpointed_value = Value{};
        nodes_[fresh].mutation_epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_relaxed);
      }
      nodes_[fresh].forward0.store(pack_forward(existing, false), std::memory_order_relaxed);

      uint64_t expected_next = pack_forward(existing, false);
      const uint64_t desired_next = pack_forward(fresh, false);
      if (nodes_[predecessor].forward0.compare_exchange_strong(
              expected_next, desired_next, std::memory_order_acq_rel)) {
        link_upper_levels(fresh, key);
        return true;
      }
    }
  }

  [[nodiscard]] auto remove(const Key &key) -> bool {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kWriter);
    Offset predecessor = kNullOffset;
    const Offset current = find_at_or_after(key, &predecessor, search_upper_levels(key).level0_hint);
    if (current == kNullOffset || current == kTail || !keys_equal(nodes_[current].key, key)) return false;

    for (;;) {
      if (nodes_[current].state.load(std::memory_order_acquire) != NodeState::kLive) {
        return false;
      }
      write_value_locked(current, [](Value &) {});  // no value change, just the shadow capture
      NodeState expected = NodeState::kLive;
      if (nodes_[current].state.compare_exchange_strong(
              expected, NodeState::kTombstonedLinked, std::memory_order_acq_rel)) {
        break;
      }
      // Lost the race to a concurrent remove() — re-check state fresh next iteration.
    }

    unlink_from_upper_levels(key, current);
    // Physical unlink (slot reuse) waits for checkpoint(): reusing the slot before this
    // removal is durable would destroy data a crash-then-recover should still fall back to.
    enqueue_pending_checkpoint_unlink(current);
    return true;
  }

  template <typename Callback>
  void scan(const Key &begin, const Key &end, Callback &&callback) const {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kReader);
    Offset predecessor = kNullOffset;
    Offset current = find_at_or_after(begin, &predecessor, search_upper_levels(begin).level0_hint);
    while (current != kNullOffset && current != kTail) {
      const auto &node = nodes_[current];
      if (!less_(node.key, end)) break;
      if (node.state.load(std::memory_order_acquire) == NodeState::kLive) {
        callback(node.key, read_value(current));
      }
      current = forward_offset(node.forward0.load(std::memory_order_acquire));
    }
  }

  void reclaim() {
    const std::lock_guard<std::mutex> epoch_lock(epoch_mutex_);

    Offset pending_head = drain_pending_unlinks();
    UpperChunk<Key> *pending_upper = pending_upper_deletes_.exchange(nullptr, std::memory_order_acq_rel);

    // Unlike checkpoint()'s writer-only wait, physical reclaim needs every reader or writer
    // that could hold a stale offset to have drained first.
    const uint64_t old_parity = epoch_.load(std::memory_order_acquire) & 1;
    epoch_.fetch_add(1, std::memory_order_acq_rel);
    auto &old_slot = epoch_slots_[old_parity];
    while (old_slot.readers.load(std::memory_order_acquire) != 0 ||
           old_slot.writers.load(std::memory_order_acquire) != 0) {
      std::this_thread::yield();
    }

    while (pending_head != kNullOffset) {
      const Offset next = forward_offset(nodes_[pending_head].forward0.load(std::memory_order_relaxed));
      free_push(pending_head);
      pending_head = next;
    }

    while (pending_upper != nullptr) {
      UpperChunk<Key> *next = pending_upper->next_pending.load(std::memory_order_relaxed);
      deallocate_upper_chunk(upper_arena_, pending_upper);
      pending_upper = next;
    }

    // Only now -- after the epoch drain above has proven no writer still holds a `current_`-
    // derived reference into a since-retired arena block -- is it safe to actually free any
    // block whose live_count reached zero (see UpperArena::release()'s comment for the race
    // this ordering closes).
    upper_arena_.drain_pending_blocks();
  }

  // Synchronous and blocking. Any put()/remove() that had already returned before this call
  // started is durable once this returns true. Concurrent checkpoint() calls serialize on
  // epoch_mutex_; only writers are waited for, so a long-running scan() never blocks this.
  [[nodiscard]] auto checkpoint() -> bool {
    const std::lock_guard<std::mutex> epoch_lock(epoch_mutex_);

    Offset pending_unlink = pending_checkpoint_unlink_.exchange(kNullOffset, std::memory_order_acq_rel);

    const uint64_t published_epoch = epoch_.load(std::memory_order_acquire);
    epoch_.fetch_add(1, std::memory_order_acq_rel);
    auto &old_slot = epoch_slots_[published_epoch & 1];
    while (old_slot.writers.load(std::memory_order_acquire) != 0) {
      std::this_thread::yield();
    }

    file_.sync();
    write_manifest(path_, published_epoch, high_water_mark_.load(std::memory_order_acquire));
    // Only after the manifest is durable — otherwise a concurrent put()/remove() could see
    // "already checkpointed" before that's true and skip a shadow recover() needs.
    last_published_epoch_.store(published_epoch, std::memory_order_release);

    while (pending_unlink != kNullOffset) {
      const Offset next = nodes_[pending_unlink].next_checkpoint_unlink.load(std::memory_order_relaxed);
      nodes_[pending_unlink].pending_checkpoint_unlink_queued.store(false, std::memory_order_release);
      physically_unlink_best_effort(nodes_[pending_unlink].key, pending_unlink);
      pending_unlink = next;
    }
    return true;
  }

 private:
  static constexpr Offset kHead = 0;
  static constexpr Offset kTail = 1;

  struct OffsetMarkedTraits {
    static constexpr auto pack(Offset id, bool marked) -> uint64_t { return pack_forward(id, marked); }
    static constexpr auto value(uint64_t raw) -> Offset { return forward_offset(raw); }
    static constexpr auto is_marked(uint64_t raw) -> bool { return forward_marked(raw); }
    static constexpr auto null_id() -> Offset { return kTail; }
  };

  void initialize_fresh() {
    ::new (&nodes_[kHead]) DurableNode<Key, Value>();
    ::new (&nodes_[kTail]) DurableNode<Key, Value>();
    nodes_[kHead].forward0.store(pack_forward(kTail, false), std::memory_order_relaxed);
  }

  // Classic seqlock read: load version, read data, fence, re-check version unchanged.
  [[nodiscard]] auto read_value(Offset offset) const -> Value {
    const auto &node = nodes_[offset];
    for (;;) {
      const uint64_t v1 = node.version.load(std::memory_order_acquire);
      if ((v1 & 1) != 0) {
        std::this_thread::yield();
        continue;
      }
      Value result = node.value;
      std::atomic_thread_fence(std::memory_order_acquire);
      if (v1 == node.version.load(std::memory_order_relaxed)) {
        return result;
      }
    }
  }

  // Claims exclusive write access to `offset`'s value (version even->odd CAS — this doubles as
  // write-side mutual exclusion against other concurrent writers of the same node, not just a
  // reader-tear guard), shadows the pre-mutation value+state on first touch since the last
  // checkpoint, runs `mutate(value)`, then releases (version -> v+2). Used by both put() (real
  // mutation) and remove() (no-op mutation — it only needs the shadow capture).
  template <typename MutateFn>
  void write_value_locked(Offset offset, MutateFn &&mutate) {
    auto &node = nodes_[offset];
    uint64_t v = node.version.load(std::memory_order_relaxed);
    for (;;) {
      if ((v & 1) != 0) {
        std::this_thread::yield();
        v = node.version.load(std::memory_order_relaxed);
        continue;
      }
      if (node.version.compare_exchange_weak(v, v + 1, std::memory_order_acq_rel, std::memory_order_relaxed)) {
        break;
      }
    }
    if (node.mutation_epoch.load(std::memory_order_acquire) <= last_published_epoch_.load(std::memory_order_acquire)) {
      node.checkpointed_value = node.value;
      node.checkpointed_state.store(node.state.load(std::memory_order_acquire), std::memory_order_relaxed);
      node.mutation_epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_relaxed);
    }
    mutate(node.value);
    node.version.store(v + 2, std::memory_order_release);
  }

  // No manifest means no checkpoint() ever completed — start fresh. Otherwise walk Level 0
  // from head, trusting nodes only while their creation epoch is <= the manifest's; the walk
  // stops and splices at the first untrusted node, and every allocated-but-unreached slot
  // below high_water_mark becomes free. A trusted node's latest value/state may still be newer
  // than the checkpoint (put() or remove(), indistinguishable here), so both are reverted to
  // their shadow whenever mutation_epoch exceeds the threshold.
  void recover() {
    const auto manifest = read_manifest(path_);
    if (!manifest.has_value()) {
      initialize_fresh();
      return;
    }

    const uint64_t threshold = manifest->epoch;
    const uint64_t recovered_high_water_mark = manifest->high_water_mark;

    // epoch_ restarts at 0 every reopen; resuming from threshold + 1 keeps epoch numbers
    // monotonic across restarts (otherwise a later recovery could wrongly trim nodes this
    // session already checkpointed).
    epoch_.store(threshold + 1, std::memory_order_relaxed);
    last_published_epoch_.store(threshold, std::memory_order_relaxed);

    std::vector<bool> reached(recovered_high_water_mark, false);
    Offset pred = kHead;
    Offset current = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (current != kTail) {
      if (current >= recovered_high_water_mark || nodes_[current].epoch.load(std::memory_order_relaxed) > threshold) {
        nodes_[pred].forward0.store(pack_forward(kTail, false), std::memory_order_relaxed);
        break;
      }
      if (nodes_[current].mutation_epoch.load(std::memory_order_relaxed) > threshold) {
        nodes_[current].value = nodes_[current].checkpointed_value;
        nodes_[current].state.store(nodes_[current].checkpointed_state.load(std::memory_order_relaxed),
                                    std::memory_order_relaxed);
        nodes_[current].mutation_epoch.store(threshold, std::memory_order_relaxed);
      }
      reached[current] = true;
      pred = current;
      current = forward_offset(nodes_[current].forward0.load(std::memory_order_relaxed));
    }

    free_head_.store(0, std::memory_order_relaxed);
    for (Offset offset = 2; offset < recovered_high_water_mark; ++offset) {
      if (!reached[offset]) {
        free_push(offset);
      }
    }

    high_water_mark_.store(recovered_high_water_mark, std::memory_order_relaxed);

    // A crash between checkpoint()'s manifest write and its (in-memory, lost) drain of
    // pending_checkpoint_unlink_ can leave an already-durable removal still TombstonedLinked;
    // nothing at runtime retries it, so finish it here in its own pass (recovery is
    // single-threaded, so this is safe; folding it into the walk above would corrupt that
    // walk's pred/current bookkeeping via find_at_or_after's own splicing).
    Offset walk = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (walk != kTail) {
      const Offset next = forward_offset(nodes_[walk].forward0.load(std::memory_order_relaxed));
      if (nodes_[walk].state.load(std::memory_order_relaxed) == NodeState::kTombstonedLinked) {
        physically_unlink_best_effort(nodes_[walk].key, walk);
      }
      walk = next;
    }

    rebuild_upper_levels();
  }

  // Upper levels are pure DRAM search hints, never persisted, so every restart rebuilds them
  // by re-linking each surviving Level 0 node exactly as put() would. O(corpus), unavoidable
  // without persisting the upper levels themselves.
  void rebuild_upper_levels() {
    Offset current = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (current != kTail) {
      link_upper_levels(current, nodes_[current].key);
      current = forward_offset(nodes_[current].forward0.load(std::memory_order_relaxed));
    }
  }

  [[nodiscard]] auto keys_equal(const Key &a, const Key &b) const -> bool { return !less_(a, b) && !less_(b, a); }

  // Traverses to the first node with key >= `key`, helping to physically unlink any marked
  // node along the way. `hint` (typically from the upper levels) seeds the first attempt in
  // place of kHead; it's safe to trust as < `key` forever, but is re-verified as still
  // unmarked before use, falling back to kHead otherwise.
  [[nodiscard]] auto find_at_or_after(const Key &key, Offset *predecessor, Offset hint = kHead) const -> Offset {
    return marked_list_find<Offset, OffsetMarkedTraits>(
        hint,
        nodes_[hint].forward0,
        kHead,
        nodes_[kHead].forward0,
        key,
        less_,
        [this](Offset o) -> std::atomic<uint64_t> & { return nodes_[o].forward0; },
        [this](Offset o) -> const Key & { return nodes_[o].key; },
        [this](Offset o) { enqueue_pending_unlink(o); },
        predecessor);
  }

  void enqueue_pending_unlink(Offset offset) const {
    stack_push(pending_head_, offset, [this](Offset o, Offset next) {
      // Mark bit stays set: clearing it would let a stale unmarked-expecting CAS from before
      // this node was removed corrupt this now-repurposed "next pending" value.
      nodes_[o].forward0.store(pack_forward(next, true), std::memory_order_relaxed);
    });
  }

  [[nodiscard]] auto drain_pending_unlinks() const -> Offset {
    return pending_head_.exchange(kNullOffset, std::memory_order_acq_rel);
  }

  // Linked via next_checkpoint_unlink, never forward0, which must keep pointing at each
  // node's real successor until checkpoint() confirms the splice is safe. The queued flag
  // guards against double-enqueue when put() resurrects a TombstonedLinked node and a later
  // remove() re-tombstones it.
  void enqueue_pending_checkpoint_unlink(Offset offset) const {
    bool expected_unqueued = false;
    if (!nodes_[offset].pending_checkpoint_unlink_queued.compare_exchange_strong(
            expected_unqueued, true, std::memory_order_acq_rel)) {
      return;
    }
    stack_push(pending_checkpoint_unlink_, offset, [this](Offset o, Offset next) {
      nodes_[o].next_checkpoint_unlink.store(next, std::memory_order_relaxed);
    });
  }

  // Tagged head (marked_offset.hpp) rules out ABA on this Treiber stack.
  void free_push(Offset offset) {
    uint64_t old_head = free_head_.load(std::memory_order_relaxed);
    for (;;) {
      nodes_[offset].forward0.store(pack_forward(tagged_offset(old_head), true), std::memory_order_relaxed);
      const uint64_t new_head = pack_tagged(offset, tagged_generation(old_head) + 1);
      if (free_head_.compare_exchange_weak(old_head, new_head, std::memory_order_acq_rel, std::memory_order_relaxed)) {
        return;
      }
    }
  }

  auto free_pop() -> Offset {
    uint64_t old_head = free_head_.load(std::memory_order_acquire);
    for (;;) {
      const Offset offset = tagged_offset(old_head);
      if (offset == 0) return kNullOffset;  // empty: offset 0 (kHead) is never freed
      const Offset next = forward_offset(nodes_[offset].forward0.load(std::memory_order_relaxed));
      const uint64_t new_head = pack_tagged(next, tagged_generation(old_head) + 1);
      if (free_head_.compare_exchange_weak(old_head, new_head, std::memory_order_acq_rel, std::memory_order_relaxed)) {
        return offset;
      }
    }
  }

  auto allocate() -> Offset {
    const Offset reused = free_pop();
    if (reused != kNullOffset) return reused;

    const Offset next = high_water_mark_.fetch_add(1, std::memory_order_relaxed);
    if (next >= capacity_slots_) {
      high_water_mark_.fetch_sub(1, std::memory_order_relaxed);
      return kNullOffset;
    }
    return next;
  }

  void physically_unlink_best_effort(const Key &key, Offset node_offset) {
    NodeState expected = NodeState::kTombstonedLinked;
    // A genuine state change (not a same-value CAS): a concurrent put() racing to resurrect
    // this node holds `expected` from before this transition, so its own CAS correctly fails
    // and retries instead of resurrecting a node this call just committed to splicing out.
    if (!nodes_[node_offset].state.compare_exchange_strong(
            expected, NodeState::kTombstonedUnlinked, std::memory_order_acq_rel)) {
      return;
    }

    marked_list_mark_for_deletion<Offset, OffsetMarkedTraits>(
        node_offset, [this](Offset o) -> std::atomic<uint64_t> & { return nodes_[o].forward0; });

    Offset predecessor = kNullOffset;
    static_cast<void>(find_at_or_after(key, &predecessor));
  }

  struct UpperSearchResult {
    Offset level0_hint = kHead;
  };

  [[nodiscard]] auto upper_word(UpperChunk<Key> *pred, int level) const -> std::atomic<uint64_t> & {
    return pred == nullptr ? upper_heads_[level - 1] : pred->forwards[level - 1];
  }

  // Whoever's splice brings levels_remaining to 0 unlinked this chunk from its last list and
  // hands it to the reclaim queue (a concurrent reader may still be mid-traversal through it).
  void on_upper_splice(UpperChunk<Key> *chunk) const {
    if (chunk->levels_remaining.fetch_sub(1, std::memory_order_acq_rel) == 1) {
      enqueue_pending_upper_delete(chunk);
    }
  }

  // Cascading top-down walk across all upper levels, comparing chunks by their immutable
  // primary_key (set once at chunk creation — see upper_chunk.hpp): at each level, positions
  // from the predecessor found one level up rather than that level's own head. Returns the
  // level-1 predecessor: the chunk with the largest primary_key strictly less than `key`, or
  // nullptr if no chunk's primary_key is < `key`. This is the read-path *hint* predecessor
  // (its offset must never be >= `key`, since find_at_or_after only ever walks forward from a
  // hint) -- it is NOT the same thing as "the chunk owning key's territory" when `key` happens
  // to equal some chunk's own primary_key exactly; see find_owning_chunk() for that. When
  // `out_anchors` is non-null, also records each level <= `height`'s incoming predecessor into
  // it — link_upper_levels()'s way of seeding every level a brand new chunk will insert into
  // without re-walking from scratch per level. When `out_current` is non-null, receives the
  // level-1 search's own return value (the first chunk found with primary_key >= `key`, or
  // nullptr) -- find_owning_chunk() uses this to detect an exact primary_key match without a
  // second traversal.
  auto cascade_upper_levels(const Key &key,
                            UpperChunk<Key> **out_anchors,
                            int height,
                            UpperChunk<Key> **out_current = nullptr) const -> UpperChunk<Key> * {
    UpperChunk<Key> *pred = nullptr;
    UpperChunk<Key> *level1_current = nullptr;
    for (int level = kDefaultMaxLevel; level >= 1; --level) {
      if (out_anchors != nullptr && level <= height) {
        out_anchors[level - 1] = pred;
      }
      UpperChunk<Key> *found_pred = nullptr;
      level1_current = find_upper_at_level_from(pred, key, level, &found_pred);
      pred = found_pred;
    }
    if (out_current != nullptr) {
      *out_current = level1_current;
    }
    return pred;
  }

  // Finds the chunk that owns `key`'s territory for insertion/removal purposes: either a chunk
  // whose primary_key exactly equals `key` (key was itself the first key ever routed to this
  // territory), or -- if none -- the predecessor chunk whose primary_key is the largest one
  // still less than `key`. Distinct from cascade_upper_levels()'s own return value, which read
  // paths need to stay strictly less than `key` for use as a Level 0 search hint; insertion and
  // removal instead need the territory match itself, including the boundary case where `key`
  // *is* the territory's own anchor.
  [[nodiscard]] auto find_owning_chunk(const Key &key) const -> UpperChunk<Key> * {
    UpperChunk<Key> *current = nullptr;
    UpperChunk<Key> *pred = cascade_upper_levels(key, nullptr, 0, &current);
    if (current != nullptr && keys_equal(current->primary_key, key)) {
      return current;
    }
    return pred;
  }

  // Scans `chunk`'s up-to-kCapacity entries for the tightest usable Level 0 hint: the largest
  // published, still-live entry key strictly less than `key`. cascade_upper_levels() guarantees
  // chunk->primary_key < key (that's what makes `chunk` the returned predecessor in the first
  // place), so the primary entry is always a valid fallback candidate and this never returns
  // kNullOffset for a non-null chunk. Only `live` entries are considered: a dead entry's
  // durable_offset may already have been physically reclaimed and reused for an unrelated key
  // once its removal is checkpointed durable, so it is not safe as a hint even though its
  // (immutable) key value would still compare correctly.
  [[nodiscard]] auto best_hint_in_chunk(UpperChunk<Key> *chunk, const Key &key) const -> Offset {
    Offset best_offset = chunk->primary_offset;
    const Key *best_key = &chunk->primary_key;
    const int claimed_count = std::min(chunk->claimed.load(std::memory_order_acquire), UpperChunk<Key>::kCapacity);
    for (int i = 0; i < claimed_count; ++i) {
      const auto &entry = chunk->entries[i];
      if (!entry.published.load(std::memory_order_acquire) || !entry.live.load(std::memory_order_acquire)) {
        continue;
      }
      if (!less_(entry.key, key)) {
        continue;  // only keys strictly less than `key` are usable hints
      }
      if (less_(*best_key, entry.key)) {
        best_key = &entry.key;
        best_offset = entry.durable_offset;
      }
    }
    return best_offset;
  }

  [[nodiscard]] auto search_upper_levels(const Key &key) const -> UpperSearchResult {
    UpperSearchResult result;
    if (UpperChunk<Key> *pred = cascade_upper_levels(key, nullptr, 0); pred != nullptr) {
      result.level0_hint = best_hint_in_chunk(pred, key);
    }
    return result;
  }

  // The one-level search cascade_upper_levels and link_upper_levels both need: stops at the
  // first chunk whose primary_key is >= `key`. `start` is the predecessor found one level up
  // (or null), never a fresh search from this level's own head.
  [[nodiscard]] auto find_upper_at_level_from(UpperChunk<Key> *start,
                                              const Key &key,
                                              int level,
                                              UpperChunk<Key> **out_pred) const -> UpperChunk<Key> * {
    return marked_list_find<UpperChunk<Key> *, PointerMarkedTraits<UpperChunk<Key>>>(
        start,
        upper_word(start, level),
        nullptr,
        upper_heads_[level - 1],
        key,
        less_,
        [level](UpperChunk<Key> *c) -> std::atomic<uint64_t> & { return c->forwards[level - 1]; },
        [](UpperChunk<Key> *c) -> const Key & { return c->primary_key; },
        [this](UpperChunk<Key> *c) { on_upper_splice(c); },
        out_pred);
  }

  // Single-level search for one specific chunk (by pointer identity, not primary_key alone,
  // since a level can hold several chunks whose primary_keys all compare less than `key`):
  // retire_chunk()'s cleanup must target the exact chunk being retired.
  [[nodiscard]] auto find_upper_chunk_at_level(UpperChunk<Key> *target,
                                               const Key &key,
                                               int level,
                                               UpperChunk<Key> **out_pred) const -> UpperChunk<Key> * {
    UpperChunk<Key> *pred = nullptr;
    UpperChunk<Key> *current =
        marked_ptr_value<UpperChunk<Key>>(upper_heads_[level - 1].load(std::memory_order_acquire));
    while (current != nullptr && !less_(key, current->primary_key)) {
      if (current == target) {
        *out_pred = pred;
        return current;
      }
      pred = current;
      current = marked_ptr_value<UpperChunk<Key>>(current->forwards[level - 1].load(std::memory_order_acquire));
    }
    *out_pred = pred;
    return nullptr;
  }

  // Tries to pack (offset, key) into an existing chunk's remaining capacity -- the fast, common
  // path for a key whose territory already has a chunk with room: an atomic slot claim and a
  // published write, no linked-list mutation at all. Returns false if `chunk` is already full
  // (every slot already claimed), in which case the caller must fall back to creating and
  // splicing in a brand new chunk.
  [[nodiscard]] auto try_insert_into_chunk(UpperChunk<Key> *chunk, Offset offset, const Key &key) -> bool {
    const int slot = chunk->claimed.fetch_add(1, std::memory_order_acq_rel);
    if (slot >= UpperChunk<Key>::kCapacity) {
      chunk->claimed.fetch_sub(1, std::memory_order_acq_rel);
      return false;
    }
    chunk->live_count.fetch_add(1, std::memory_order_acq_rel);
    auto &entry = chunk->entries[slot];
    entry.key = key;
    entry.durable_offset = offset;
    entry.live.store(true, std::memory_order_relaxed);
    entry.published.store(true, std::memory_order_release);

    // Mirrors link_upper_levels()'s own self-heal below: a concurrent remove() may have
    // tombstoned `offset` while this call was still claiming/publishing its slot, and (since
    // this entry didn't exist in any chunk until the publish store above) that remove()'s own
    // scan of this chunk could not have found it yet. If so, retire this one entry ourselves --
    // the CAS ensures only one of {this self-heal, a genuinely concurrent remove() that now
    // finds the freshly published entry} actually decrements live_count.
    if (nodes_[offset].state.load(std::memory_order_acquire) != NodeState::kLive) {
      bool expected_live = true;
      if (entry.live.compare_exchange_strong(expected_live, false, std::memory_order_acq_rel) &&
          chunk->live_count.fetch_sub(1, std::memory_order_acq_rel) == 1) {
        retire_chunk(chunk, key);
      }
    }
    return true;
  }

  void link_upper_levels(Offset fresh, const Key &key) {
    if (nodes_[fresh].state.load(std::memory_order_acquire) != NodeState::kLive) {
      // A concurrent remove() already tombstoned `fresh` before this began -- nothing to link.
      return;
    }

    if (UpperChunk<Key> *owner = find_owning_chunk(key); owner != nullptr) {
      if (try_insert_into_chunk(owner, fresh, key)) {
        return;  // fast path: packed into an existing chunk, no linked-list mutation needed
      }
    }

    // Slow path: the predecessor's chunk (if any) is full, or there is no chunk at all yet for
    // this territory -- create a fresh chunk seeded with just this one key and splice it into
    // the outer linked list, exactly as the original one-key-per-node design always did. This
    // incidentally subdivides whatever territory it lands in going forward; older entries
    // already packed into a full chunk are never rebalanced (see upper_chunk.hpp).
    const int height = level_generator_.next_level();
    UpperChunk<Key> *chunk = allocate_upper_chunk(upper_arena_, fresh, key, height);

    std::array<UpperChunk<Key> *, kDefaultMaxLevel> anchors{};
    cascade_upper_levels(key, anchors.data(), height);

    // Bottom-up insert into levels 1..height (ASCS insert order), reusing each level's cached
    // anchor across CAS retries — usually still a shortcut, correct even when stale.
    for (int level = 1; level <= height; ++level) {
      UpperChunk<Key> *hint = anchors[static_cast<size_t>(level - 1)];
      for (;;) {
        UpperChunk<Key> *found_pred = nullptr;
        UpperChunk<Key> *successor = find_upper_at_level_from(hint, key, level, &found_pred);
        chunk->forwards[level - 1].store(pack_marked_ptr(successor, false), std::memory_order_relaxed);
        uint64_t expected = pack_marked_ptr(successor, false);
        const uint64_t desired = pack_marked_ptr(chunk, false);
        if (upper_word(found_pred, level).compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
          break;
        }
      }
    }

    // A concurrent remove() may have tombstoned `fresh` at any point during the insertion loop
    // above; its own unlink attempt (unlink_from_upper_levels(), which needs to find this
    // chunk via the same cascade_upper_levels() search) could not have found a chunk that
    // hadn't finished being spliced in yet. Re-checking state now and self-healing closes that
    // race without needing any liveness signal cached separately: whichever of {this call,
    // remove()'s own call} finishes last is guaranteed to observe every level already inserted
    // (this call's insertion loop has just finished them all), so it alone is enough to catch
    // anything the other missed.
    if (nodes_[fresh].state.load(std::memory_order_acquire) != NodeState::kLive) {
      bool expected_live = true;
      if (chunk->entries[0].live.compare_exchange_strong(expected_live, false, std::memory_order_acq_rel) &&
          chunk->live_count.fetch_sub(1, std::memory_order_acq_rel) == 1) {
        retire_chunk(chunk, key);
      }
    }
  }

  // Marks one specific entry (matched by durable_offset) inside the chunk responsible for
  // `key`'s territory as no longer live. A chunk's primary_key never changes, so the same
  // find_owning_chunk() routing link_upper_levels() used to place this key will always find the
  // same chunk. Once a chunk's last live entry is gone, retires the whole chunk from every level
  // it participates in (retire_chunk()) and queues it for EBR reclaim.
  void unlink_from_upper_levels(const Key &key, Offset target_offset) {
    UpperChunk<Key> *chunk = find_owning_chunk(key);
    if (chunk == nullptr) {
      return;  // defensive: every live key's chunk is found by the exact routing it was
               // inserted with, so this should not happen in practice.
    }
    const int claimed_count = std::min(chunk->claimed.load(std::memory_order_acquire), UpperChunk<Key>::kCapacity);
    for (int i = 0; i < claimed_count; ++i) {
      auto &entry = chunk->entries[i];
      if (!entry.published.load(std::memory_order_acquire) || entry.durable_offset != target_offset) {
        continue;
      }
      bool expected_live = true;
      if (entry.live.compare_exchange_strong(expected_live, false, std::memory_order_acq_rel) &&
          chunk->live_count.fetch_sub(1, std::memory_order_acq_rel) == 1) {
        retire_chunk(chunk, key);
      }
      return;
    }
  }

  // Eager top-down splice of one whole chunk's outer-linked-list entries, called once every
  // entry it ever held has been removed (from unlink_from_upper_levels()/try_insert_into_chunk()/
  // link_upper_levels()'s self-heal, whichever happens to decrement live_count to 0). Idempotent
  // against a level another caller already spliced -- find_upper_chunk_at_level() simply won't
  // find it there any more.
  void retire_chunk(UpperChunk<Key> *target, const Key &key) {
    for (int level = kDefaultMaxLevel; level >= 1; --level) {
      UpperChunk<Key> *pred = nullptr;
      UpperChunk<Key> *current = find_upper_chunk_at_level(target, key, level, &pred);
      if (current == nullptr) {
        continue;
      }
      marked_list_mark_for_deletion<UpperChunk<Key> *, PointerMarkedTraits<UpperChunk<Key>>>(
          current, [level](UpperChunk<Key> *c) -> std::atomic<uint64_t> & { return c->forwards[level - 1]; });
      const uint64_t successor_raw = current->forwards[level - 1].load(std::memory_order_acquire);
      uint64_t expected = pack_marked_ptr(current, false);
      const uint64_t desired = pack_marked_ptr(marked_ptr_value<UpperChunk<Key>>(successor_raw), false);
      if (upper_word(pred, level).compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
        on_upper_splice(current);
      }
    }
  }

  void enqueue_pending_upper_delete(UpperChunk<Key> *chunk) const {
    stack_push(pending_upper_deletes_, chunk, [](UpperChunk<Key> *c, UpperChunk<Key> *next) {
      c->next_pending.store(next, std::memory_order_relaxed);
    });
  }

  std::filesystem::path path_;
  MmapFile file_;
  DurableNode<Key, Value> *nodes_;
  size_t capacity_slots_;
  std::atomic<Offset> high_water_mark_{2};
  Compare less_{};
  LevelGenerator level_generator_;
  // mutable: search functions are logically const (they only ever refine a hint) but
  // physically mutate these via helping splices and reclaim-queue pushes.
  mutable std::array<std::atomic<uint64_t>, kDefaultMaxLevel> upper_heads_{};
  mutable std::atomic<UpperChunk<Key> *> pending_upper_deletes_{nullptr};
  // Backs every UpperNode allocation (see upper_arena.hpp) -- only ever touched from mutating
  // contexts (link_upper_levels(), the destructor, reclaim()), so unlike the members above this
  // needs no `mutable`.
  UpperArena upper_arena_;

  mutable std::array<EpochSlot, 2> epoch_slots_{};
  mutable std::atomic<uint64_t> epoch_{0};
  std::mutex epoch_mutex_;
  mutable std::atomic<Offset> pending_head_{kNullOffset};
  std::atomic<uint64_t> free_head_{0};

  // Epoch of the last successful checkpoint() — distinct from epoch_, which reclaim() also
  // bumps for EBR purposes.
  mutable std::atomic<uint64_t> last_published_epoch_{0};
  mutable std::atomic<Offset> pending_checkpoint_unlink_{kNullOffset};
};

}  // namespace pskiplist

#define PSKIPLIST_VERSION_MAJOR 0
#define PSKIPLIST_VERSION_MINOR 1
#define PSKIPLIST_VERSION_PATCH 0
#define PSKIPLIST_VERSION (PSKIPLIST_VERSION_MAJOR * 10000 + PSKIPLIST_VERSION_MINOR * 100 + PSKIPLIST_VERSION_PATCH)

