// Generated by scripts/amalgamate.sh from include/pskiplist/detail/*.hpp. Do not edit
// directly — edit the sources under detail/ and regenerate.
#pragma once

#define PSKIPLIST_VERSION_MAJOR 0
#define PSKIPLIST_VERSION_MINOR 1
#define PSKIPLIST_VERSION_PATCH 0
#define PSKIPLIST_VERSION \
  (PSKIPLIST_VERSION_MAJOR * 10000 + PSKIPLIST_VERSION_MINOR * 100 + PSKIPLIST_VERSION_PATCH)

#include <concepts>
#include <type_traits>

namespace pskiplist {

// Key is stored as raw bytes directly in the mmap'd file (2.1節) and is never
// placement-new constructed slot-by-slot — only trivially copyable types can be safely
// read from and overwritten onto memory that was never explicitly constructed.
template <typename Key>
concept SkipListKey = std::is_trivially_copyable_v<Key> && std::default_initializable<Key>;

template <typename Compare, typename Key>
concept SkipListCompare =
    std::default_initializable<Compare> && std::predicate<Compare, const Key &, const Key &>;

}  // namespace pskiplist

#include <cstdint>

namespace pskiplist {

using Offset = uint64_t;
inline constexpr uint64_t kForwardMarkBit = uint64_t{1} << 63;
inline constexpr Offset kNullOffset = kForwardMarkBit - 1;

[[nodiscard]] inline constexpr auto pack_forward(Offset offset, bool marked) -> uint64_t {
  return offset | (marked ? kForwardMarkBit : uint64_t{0});
}
[[nodiscard]] inline constexpr auto forward_offset(uint64_t raw) -> Offset { return raw & ~kForwardMarkBit; }
[[nodiscard]] inline constexpr auto forward_marked(uint64_t raw) -> bool { return (raw & kForwardMarkBit) != 0; }

// A tagged (offset, generation counter) pair packed into one word, for the free list's
// Treiber stack head: the counter changes on every push and pop so a thread that stalls
// mid-pop with a stale head value can never CAS it back in undetected, even if the exact
// same offset has since been popped and pushed again (the classic ABA hazard for a plain
// offset-only stack head). 24 bits of counter is generous — wrapping it back to a value
// a stalled thread could still match would need that many free-list push/pop cycles to
// land on the same offset again during a single stall, which isn't realistic. 40 bits of
// offset is equally generous for node counts.
inline constexpr int kTaggedOffsetBits = 40;
inline constexpr uint64_t kTaggedOffsetMask = (uint64_t{1} << kTaggedOffsetBits) - 1;
inline constexpr Offset kMaxTaggedOffset = kTaggedOffsetMask;

[[nodiscard]] inline constexpr auto pack_tagged(Offset offset, uint32_t tag) -> uint64_t {
  return (offset & kTaggedOffsetMask) | (static_cast<uint64_t>(tag) << kTaggedOffsetBits);
}
[[nodiscard]] inline constexpr auto tagged_offset(uint64_t raw) -> Offset { return raw & kTaggedOffsetMask; }
[[nodiscard]] inline constexpr auto tagged_generation(uint64_t raw) -> uint32_t {
  return static_cast<uint32_t>(raw >> kTaggedOffsetBits);
}

}  // namespace pskiplist

#include <cstdint>

namespace pskiplist {

enum class NodeState : uint8_t {
  kLive = 0,
  kTombstonedLinked = 1,
  kTombstonedUnlinked = 2,
};

class PackedValue {
 public:
  PackedValue() = default;
  explicit PackedValue(uint64_t bits) : bits_(bits) {}
  static auto live(uint64_t payload) -> PackedValue { return PackedValue(encode(NodeState::kLive, payload)); }

  [[nodiscard]] auto state() const -> NodeState { return static_cast<NodeState>(bits_ >> kPayloadBits); }
  [[nodiscard]] auto payload() const -> uint64_t { return bits_ & kPayloadMask; }
  [[nodiscard]] auto raw() const -> uint64_t { return bits_; }
  [[nodiscard]] auto with_state(NodeState state) const -> PackedValue { return PackedValue(encode(state, payload())); }

  static constexpr int kPayloadBits = 62;
  static constexpr uint64_t kPayloadMask = (uint64_t{1} << kPayloadBits) - 1;

 private:
  static auto encode(NodeState state, uint64_t payload) -> uint64_t {
    return (static_cast<uint64_t>(state) << kPayloadBits) | (payload & kPayloadMask);
  }
  uint64_t bits_ = 0;
};

}  // namespace pskiplist

#include <atomic>
#include <cstdint>

namespace pskiplist {

template <typename Key>
struct DurableNode {
  std::atomic<uint64_t> epoch{0};
  Key key{};
  std::atomic<uint64_t> value{0};
  mutable std::atomic<uint64_t> forward0{pack_forward(kNullOffset, false)};
};

}  // namespace pskiplist

#include <array>
#include <atomic>
#include <cstdint>

namespace pskiplist {

enum class EpochRole : uint8_t {
  kReader,
  kWriter,
};

// Per-parity-slot active counts, split by role. reclaim() (2.3節) waits for both readers
// and writers in a slot to drain, since either could hold a stale offset reference to a
// node about to be freed. checkpoint() (3章) waits only for writers, since a concurrent
// reader never mutates anything msync() could tear.
struct EpochSlot {
  std::atomic<int64_t> readers{0};
  std::atomic<int64_t> writers{0};
};

// RAII registration for a 2-slot epoch-based reclamation scheme: registers into whichever
// of `slots[0]`/`slots[1]` matches the current parity of `epoch` for the token's lifetime,
// under the counter matching `role`. Whoever advances `epoch` and waits for the slot the
// advance vacated to drain treats anything observed under it as safe to act on.
class EpochToken {
 public:
  EpochToken(std::array<EpochSlot, 2> &slots, std::atomic<uint64_t> &epoch, EpochRole role)
      : slots_(slots), role_(role) {
    parity_ = epoch.load(std::memory_order_acquire) & 1;
    counter().fetch_add(1, std::memory_order_acq_rel);
  }
  ~EpochToken() { counter().fetch_sub(1, std::memory_order_acq_rel); }
  EpochToken(const EpochToken &) = delete;
  auto operator=(const EpochToken &) -> EpochToken & = delete;

 private:
  [[nodiscard]] auto counter() -> std::atomic<int64_t> & {
    return role_ == EpochRole::kReader ? slots_[parity_].readers : slots_[parity_].writers;
  }

  std::array<EpochSlot, 2> &slots_;
  EpochRole role_;
  uint64_t parity_;
};

}  // namespace pskiplist

#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <optional>
#include <system_error>

#include <fcntl.h>
#include <unistd.h>

namespace pskiplist {

inline constexpr uint32_t kManifestMagic = 0x504b4c31;  // "PKL1"
inline constexpr uint8_t kManifestFormatVersion = 1;

// 32B fixed manifest header (3章). A mismatched format_version is treated identically to
// a missing manifest — no migration is implemented.
struct ManifestHeader {
  uint32_t magic = kManifestMagic;
  uint8_t format_version = kManifestFormatVersion;
  uint8_t reserved[3] = {};
  uint64_t epoch = 0;           // node epoch stamps <= this are trusted as durable
  uint64_t high_water_mark = 0;  // bump allocation's last reached offset
  uint64_t checksum = 0;        // FNV-1a64 of this header with checksum itself zeroed
};
static_assert(sizeof(ManifestHeader) == 32);

[[nodiscard]] inline auto manifest_checksum(const ManifestHeader &header) -> uint64_t {
  ManifestHeader zeroed = header;
  zeroed.checksum = 0;
  const auto *bytes = reinterpret_cast<const unsigned char *>(&zeroed);
  uint64_t hash = 0xcbf29ce484222325ULL;
  for (size_t i = 0; i < sizeof(zeroed); ++i) {
    hash ^= bytes[i];
    hash *= 0x100000001b3ULL;
  }
  return hash;
}

[[nodiscard]] inline auto manifest_path(const std::filesystem::path &data_path) -> std::filesystem::path {
  auto path = data_path;
  path += ".manifest";
  return path;
}

// Writes the manifest for `data_path` via temp file + fsync + atomic rename (3章), so a
// reader never observes a partially-written manifest.
inline void write_manifest(const std::filesystem::path &data_path, uint64_t epoch, uint64_t high_water_mark) {
  ManifestHeader header;
  header.epoch = epoch;
  header.high_water_mark = high_water_mark;
  header.checksum = manifest_checksum(header);

  const auto final_path = manifest_path(data_path);
  auto tmp_path = final_path;
  tmp_path += ".tmp";

  const int fd = ::open(tmp_path.c_str(), O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if (fd < 0) {
    throw std::system_error(errno, std::generic_category(), "open(" + tmp_path.string() + ")");
  }
  const ssize_t written = ::write(fd, &header, sizeof(header));
  if (written != static_cast<ssize_t>(sizeof(header))) {
    const int err = errno;
    ::close(fd);
    throw std::system_error(err, std::generic_category(), "write(" + tmp_path.string() + ")");
  }
  if (::fsync(fd) != 0) {
    const int err = errno;
    ::close(fd);
    throw std::system_error(err, std::generic_category(), "fsync(" + tmp_path.string() + ")");
  }
  ::close(fd);

  std::error_code ec;
  std::filesystem::rename(tmp_path, final_path, ec);
  if (ec) {
    throw std::system_error(ec, "rename(" + tmp_path.string() + " -> " + final_path.string() + ")");
  }
}

// Returns nullopt if the manifest is missing, truncated, has a mismatched magic or
// format_version, or fails its checksum — any of these are treated as "no checkpoint has
// ever completed for this file".
[[nodiscard]] inline auto read_manifest(const std::filesystem::path &data_path) -> std::optional<ManifestHeader> {
  const auto path = manifest_path(data_path);
  const int fd = ::open(path.c_str(), O_RDONLY);
  if (fd < 0) return std::nullopt;

  ManifestHeader header{};
  const ssize_t bytes_read = ::read(fd, &header, sizeof(header));
  ::close(fd);
  if (bytes_read != static_cast<ssize_t>(sizeof(header))) return std::nullopt;
  if (header.magic != kManifestMagic) return std::nullopt;
  if (header.format_version != kManifestFormatVersion) return std::nullopt;
  if (manifest_checksum(header) != header.checksum) return std::nullopt;

  return header;
}

}  // namespace pskiplist

#include <cstddef>
#include <filesystem>
#include <stdexcept>
#include <system_error>

#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

namespace pskiplist {

// RAII POSIX file opened, sized, and mapped MAP_SHARED for direct in-place mutation.
// Sized once at construction and never grown (2.6節). A brand-new (empty) file is
// zero-extended to size_bytes; an existing non-empty file's content is preserved as-is
// (recovery, 3章, decides what in it to trust) and must already be exactly size_bytes —
// a mismatch is a construction error, not something this class silently resolves.
class MmapFile {
 public:
  MmapFile(const std::filesystem::path &path, size_t size_bytes) : size_(size_bytes) {
    fd_ = ::open(path.c_str(), O_RDWR | O_CREAT, 0644);
    if (fd_ < 0) {
      throw std::system_error(errno, std::generic_category(), "open(" + path.string() + ")");
    }

    struct stat st {};
    if (::fstat(fd_, &st) != 0) {
      const int err = errno;
      ::close(fd_);
      throw std::system_error(err, std::generic_category(), "fstat(" + path.string() + ")");
    }

    if (st.st_size == 0) {
      if (::ftruncate(fd_, static_cast<off_t>(size_)) != 0) {
        const int err = errno;
        ::close(fd_);
        throw std::system_error(err, std::generic_category(), "ftruncate(" + path.string() + ")");
      }
    } else {
      reused_ = true;
      if (static_cast<size_t>(st.st_size) != size_) {
        ::close(fd_);
        throw std::invalid_argument("pskiplist: " + path.string() + " exists with a size that does not match capacity_bytes");
      }
    }

    data_ = ::mmap(nullptr, size_, PROT_READ | PROT_WRITE, MAP_SHARED, fd_, 0);
    if (data_ == MAP_FAILED) {
      const int err = errno;
      ::close(fd_);
      throw std::system_error(err, std::generic_category(), "mmap(" + path.string() + ")");
    }
  }

  ~MmapFile() {
    if (data_ != nullptr && data_ != MAP_FAILED) {
      ::munmap(data_, size_);
    }
    if (fd_ >= 0) {
      ::close(fd_);
    }
  }

  MmapFile(const MmapFile &) = delete;
  auto operator=(const MmapFile &) -> MmapFile & = delete;

  [[nodiscard]] auto data() const -> void * { return data_; }
  [[nodiscard]] auto size() const -> size_t { return size_; }
  // True if `path` already existed with content (i.e. wasn't freshly created) —
  // PSkipList uses this to decide whether to run recovery instead of a fresh init.
  [[nodiscard]] auto reused() const -> bool { return reused_; }

  // Blocks until the mapping's dirty pages are durable on the underlying storage (3章).
  void sync() const {
    if (::msync(data_, size_, MS_SYNC) != 0) {
      throw std::system_error(errno, std::generic_category(), "msync");
    }
  }

 private:
  int fd_ = -1;
  void *data_ = nullptr;
  size_t size_ = 0;
  bool reused_ = false;
};

}  // namespace pskiplist

#include <array>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <mutex>
#include <new>
#include <optional>
#include <stdexcept>
#include <thread>
#include <vector>

namespace pskiplist {

template <typename Key, typename Compare = std::less<Key>>
  requires SkipListKey<Key> && SkipListCompare<Compare, Key>
class PSkipList {
 public:
  // `capacity_bytes` is fixed for the lifetime of the mapping (2.6節) — sized generously
  // up front, since a sparse file only consumes disk for pages actually written. The data
  // file at `path` is mutated in place via MAP_SHARED; it is not rewritten on checkpoint.
  explicit PSkipList(const std::filesystem::path &path, size_t capacity_bytes)
      : path_(path),
        file_(path, capacity_bytes),
        nodes_(static_cast<DurableNode<Key> *>(file_.data())),
        capacity_slots_(file_.size() / sizeof(DurableNode<Key>)) {
    if (capacity_slots_ < 2) {
      throw std::invalid_argument("pskiplist: capacity_bytes too small to hold head/tail sentinels");
    }
    if (capacity_slots_ > kMaxTaggedOffset) {
      throw std::invalid_argument("pskiplist: capacity_bytes exceeds the maximum representable node count");
    }
    if (file_.reused()) {
      recover();
    } else {
      initialize_fresh();
    }
  }

  PSkipList(const PSkipList &) = delete;
  auto operator=(const PSkipList &) -> PSkipList & = delete;

  [[nodiscard]] auto get(const Key &key) const -> std::optional<uint64_t> {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kReader);
    Offset predecessor = kNullOffset;
    const Offset current = find_at_or_after(key, &predecessor);
    if (current == kNullOffset || current == kTail || !keys_equal(nodes_[current].key, key)) {
      return std::nullopt;
    }
    const PackedValue v(nodes_[current].value.load(std::memory_order_acquire));
    if (v.state() != NodeState::kLive) return std::nullopt;
    return v.payload();
  }

  [[nodiscard]] auto put(const Key &key, uint64_t payload) -> bool {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kWriter);
    Offset fresh = kNullOffset;
    for (;;) {
      Offset predecessor = kNullOffset;
      const Offset existing = find_at_or_after(key, &predecessor);
      if (existing != kNullOffset && existing != kTail && keys_equal(nodes_[existing].key, key)) {
        uint64_t expected = nodes_[existing].value.load(std::memory_order_acquire);
        if (PackedValue(expected).state() == NodeState::kTombstonedUnlinked) {
          std::this_thread::yield();
          continue;
        }
        const uint64_t desired = PackedValue::live(payload).raw();
        if (nodes_[existing].value.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
          return true;
        }
        continue;
      }

      if (fresh == kNullOffset) {
        fresh = allocate();
        if (fresh == kNullOffset) return false;
        nodes_[fresh].key = key;
        nodes_[fresh].value.store(PackedValue::live(payload).raw(), std::memory_order_relaxed);
        nodes_[fresh].epoch.store(epoch_.load(std::memory_order_acquire), std::memory_order_relaxed);
      }
      nodes_[fresh].forward0.store(pack_forward(existing, false), std::memory_order_relaxed);

      uint64_t expected_next = pack_forward(existing, false);
      const uint64_t desired_next = pack_forward(fresh, false);
      if (nodes_[predecessor].forward0.compare_exchange_strong(expected_next, desired_next, std::memory_order_acq_rel)) {
        return true;
      }
    }
  }

  [[nodiscard]] auto remove(const Key &key) -> bool {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kWriter);
    Offset predecessor = kNullOffset;
    const Offset current = find_at_or_after(key, &predecessor);
    if (current == kNullOffset || current == kTail || !keys_equal(nodes_[current].key, key)) return false;

    for (;;) {
      uint64_t expected = nodes_[current].value.load(std::memory_order_acquire);
      const PackedValue v(expected);
      if (v.state() != NodeState::kLive) return false;
      const uint64_t desired = v.with_state(NodeState::kTombstonedLinked).raw();
      if (nodes_[current].value.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
        break;
      }
    }

    physically_unlink_best_effort(key, current);
    return true;
  }

  template <typename Callback>
  void scan(const Key &begin, const Key &end, Callback &&callback) const {
    const EpochToken token(epoch_slots_, epoch_, EpochRole::kReader);
    Offset predecessor = kNullOffset;
    Offset current = find_at_or_after(begin, &predecessor);
    while (current != kNullOffset && current != kTail) {
      const auto &node = nodes_[current];
      if (!less_(node.key, end)) break;
      const PackedValue v(node.value.load(std::memory_order_acquire));
      if (v.state() == NodeState::kLive) {
        callback(node.key, v.payload());
      }
      current = forward_offset(node.forward0.load(std::memory_order_acquire));
    }
  }

  void reclaim() {
    const std::lock_guard<std::mutex> epoch_lock(epoch_mutex_);

    // Take exclusive ownership of every offset currently pending unlink; nothing else
    // will touch these nodes' forward0 links until free_push() below repurposes them.
    Offset pending_head = drain_pending_unlinks();

    // Physical-reclaim safety needs every possible holder of a stale offset — reader or
    // writer — to have drained, unlike checkpoint()'s writer-only wait (3章).
    const uint64_t old_parity = epoch_.load(std::memory_order_acquire) & 1;
    epoch_.fetch_add(1, std::memory_order_acq_rel);
    auto &old_slot = epoch_slots_[old_parity];
    while (old_slot.readers.load(std::memory_order_acquire) != 0 ||
           old_slot.writers.load(std::memory_order_acquire) != 0) {
      std::this_thread::yield();
    }

    while (pending_head != kNullOffset) {
      const Offset next = forward_offset(nodes_[pending_head].forward0.load(std::memory_order_relaxed));
      free_push(pending_head);
      pending_head = next;
    }
  }

  // Synchronous and blocking. Any put()/remove() that had already returned before this
  // call started is durable once this returns true; whether one that started during the
  // call is durable is unspecified. Concurrent checkpoint() calls are serialized on
  // epoch_mutex_. Only writers are waited for — a long-running scan() never blocks this.
  [[nodiscard]] auto checkpoint() -> bool {
    const std::lock_guard<std::mutex> epoch_lock(epoch_mutex_);

    const uint64_t published_epoch = epoch_.load(std::memory_order_acquire);
    epoch_.fetch_add(1, std::memory_order_acq_rel);
    auto &old_slot = epoch_slots_[published_epoch & 1];
    while (old_slot.writers.load(std::memory_order_acquire) != 0) {
      std::this_thread::yield();
    }

    file_.sync();
    write_manifest(path_, published_epoch, high_water_mark_.load(std::memory_order_acquire));
    return true;
  }

 private:
  static constexpr Offset kHead = 0;
  static constexpr Offset kTail = 1;

  void initialize_fresh() {
    ::new (&nodes_[kHead]) DurableNode<Key>();
    ::new (&nodes_[kTail]) DurableNode<Key>();
    nodes_[kHead].forward0.store(pack_forward(kTail, false), std::memory_order_relaxed);
  }

  // Called only when the backing file already had content. No manifest means no
  // checkpoint() ever completed for this file, so nothing in it is trusted — start fresh
  // exactly as a brand-new file would. Otherwise, walk Level 0 from head, trusting nodes
  // in encounter order only while their epoch stamp is <= the manifest's: a node past
  // that point may have been concurrently written by a writer checkpoint() didn't wait
  // for, so neither it nor anything reachable only through it is trustworthy, and the
  // walk stops there, splicing the chain to end at that point. Every allocated slot
  // (2章) below the manifest's high_water_mark that the walk didn't reach — whether never
  // linked in, or unlinked-but-not-yet-reclaimed before the crash — becomes free (2.3節's
  // mark-and-sweep). high_water_mark_ rolls back to the manifest's value: any allocation
  // racing the checkpoint that isn't captured by it is simply not recovered.
  void recover() {
    const auto manifest = read_manifest(path_);
    if (!manifest.has_value()) {
      initialize_fresh();
      return;
    }

    const uint64_t threshold = manifest->epoch;
    const uint64_t recovered_high_water_mark = manifest->high_water_mark;

    std::vector<bool> reached(recovered_high_water_mark, false);
    Offset pred = kHead;
    Offset current = forward_offset(nodes_[kHead].forward0.load(std::memory_order_relaxed));
    while (current != kTail) {
      if (current >= recovered_high_water_mark ||
          nodes_[current].epoch.load(std::memory_order_relaxed) > threshold) {
        nodes_[pred].forward0.store(pack_forward(kTail, false), std::memory_order_relaxed);
        break;
      }
      reached[current] = true;
      pred = current;
      current = forward_offset(nodes_[current].forward0.load(std::memory_order_relaxed));
    }

    free_head_.store(0, std::memory_order_relaxed);
    for (Offset offset = 2; offset < recovered_high_water_mark; ++offset) {
      if (!reached[offset]) {
        free_push(offset);
      }
    }

    high_water_mark_.store(recovered_high_water_mark, std::memory_order_relaxed);
  }

  [[nodiscard]] auto keys_equal(const Key &a, const Key &b) const -> bool {
    return !less_(a, b) && !less_(b, a);
  }

  // Traverses to the first node with key >= `key`, helping to physically unlink any
  // marked (logically deleted) node it encounters along the way (4.2節). A helping CAS
  // that wins pushes the unlinked node to the pending-unlink queue; on any CAS outcome
  // touching a marked node the whole search restarts from head, since a stale predecessor
  // can no longer be trusted.
  [[nodiscard]] auto find_at_or_after(const Key &key, Offset *predecessor) const -> Offset {
    for (;;) {
      Offset pred = kHead;
      Offset current = forward_offset(nodes_[pred].forward0.load(std::memory_order_acquire));
      for (;;) {
        if (current == kTail) {
          *predecessor = pred;
          return current;
        }
        const uint64_t current_raw = nodes_[current].forward0.load(std::memory_order_acquire);
        if (forward_marked(current_raw)) {
          const Offset successor = forward_offset(current_raw);
          uint64_t expected = pack_forward(current, false);
          const uint64_t desired = pack_forward(successor, false);
          if (nodes_[pred].forward0.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
            enqueue_pending_unlink(current);
          }
          break;  // restart the whole search from head
        }
        if (!less_(nodes_[current].key, key)) {
          *predecessor = pred;
          return current;
        }
        pred = current;
        current = forward_offset(current_raw);
      }
    }
  }

  // Lock-free multi-producer stack: any number of unlinkers push concurrently, and
  // reclaim() drains the whole thing with a single atomic exchange. There's no per-item
  // pop here, so there's no ABA hazard to guard against — unlike the free list below.
  void enqueue_pending_unlink(Offset offset) const {
    Offset old_head = pending_head_.load(std::memory_order_relaxed);
    do {
      // Keep the mark bit set: this word is already frozen against any stale unmarked-
      // expecting CAS from a thread that read this node before it was ever removed (4.2節)
      // — clearing it here would let such a CAS coincidentally match this repurposed
      // "next pending" value and corrupt the chain.
      nodes_[offset].forward0.store(pack_forward(old_head, true), std::memory_order_relaxed);
    } while (!pending_head_.compare_exchange_weak(old_head, offset, std::memory_order_acq_rel,
                                                   std::memory_order_relaxed));
  }

  [[nodiscard]] auto drain_pending_unlinks() const -> Offset {
    return pending_head_.exchange(kNullOffset, std::memory_order_acq_rel);
  }

  // Lock-free Treiber stack with a tagged head (marked_offset.hpp) to rule out ABA: a
  // freed node's own forward0 becomes the "next free" link, safe to repurpose since
  // nothing reaches it through the live chain anymore.
  void free_push(Offset offset) {
    uint64_t old_head = free_head_.load(std::memory_order_relaxed);
    for (;;) {
      // Marked for the same reason as enqueue_pending_unlink above.
      nodes_[offset].forward0.store(pack_forward(tagged_offset(old_head), true), std::memory_order_relaxed);
      const uint64_t new_head = pack_tagged(offset, tagged_generation(old_head) + 1);
      if (free_head_.compare_exchange_weak(old_head, new_head, std::memory_order_acq_rel,
                                            std::memory_order_relaxed)) {
        return;
      }
    }
  }

  auto free_pop() -> Offset {
    uint64_t old_head = free_head_.load(std::memory_order_acquire);
    for (;;) {
      const Offset offset = tagged_offset(old_head);
      if (offset == 0) return kNullOffset;  // empty: offset 0 (kHead) is never freed
      const Offset next = forward_offset(nodes_[offset].forward0.load(std::memory_order_relaxed));
      const uint64_t new_head = pack_tagged(next, tagged_generation(old_head) + 1);
      if (free_head_.compare_exchange_weak(old_head, new_head, std::memory_order_acq_rel,
                                            std::memory_order_relaxed)) {
        return offset;
      }
    }
  }

  auto allocate() -> Offset {
    const Offset reused = free_pop();
    if (reused != kNullOffset) return reused;

    const Offset next = high_water_mark_.fetch_add(1, std::memory_order_relaxed);
    if (next >= capacity_slots_) {
      high_water_mark_.fetch_sub(1, std::memory_order_relaxed);
      return kNullOffset;
    }
    return next;
  }

  void physically_unlink_best_effort(const Key &key, Offset node_offset) {
    uint64_t expected = nodes_[node_offset].value.load(std::memory_order_acquire);
    const PackedValue v(expected);
    if (v.state() != NodeState::kTombstonedLinked) return;
    const uint64_t desired = v.with_state(NodeState::kTombstonedUnlinked).raw();
    if (!nodes_[node_offset].value.compare_exchange_strong(expected, desired, std::memory_order_acq_rel)) {
      return;
    }

    uint64_t forward_raw = nodes_[node_offset].forward0.load(std::memory_order_acquire);
    while (!forward_marked(forward_raw)) {
      const uint64_t marked = pack_forward(forward_offset(forward_raw), true);
      if (nodes_[node_offset].forward0.compare_exchange_strong(forward_raw, marked, std::memory_order_acq_rel)) {
        break;
      }
    }

    Offset predecessor = kNullOffset;
    static_cast<void>(find_at_or_after(key, &predecessor));
  }

  std::filesystem::path path_;
  MmapFile file_;
  DurableNode<Key> *nodes_;
  size_t capacity_slots_;
  std::atomic<Offset> high_water_mark_{2};
  Compare less_{};

  mutable std::array<EpochSlot, 2> epoch_slots_{};
  mutable std::atomic<uint64_t> epoch_{0};
  std::mutex epoch_mutex_;
  mutable std::atomic<Offset> pending_head_{kNullOffset};
  std::atomic<uint64_t> free_head_{0};
};

}  // namespace pskiplist

